project_id = "izwimkvabbvnqcrrubpf"

[functions.send-manager-credentials]
verify_jwt = false

[functions.verify-manager-login]
verify_jwt = false

[functions.process-manager-decision]
verify_jwt = false

[functions.withdraw-approval-request]
verify_jwt = false

[functions.create-panel-reviewer]
verify_jwt = false

[functions.send-reviewer-invitation]
verify_jwt = false

[functions.cancel-reviewer-invitation]
verify_jwt = false
