/**
 * Pass3AttributionBadge — UI-only badge shown beneath the Legal Doc editor
 * after Pass 3 is accepted. Resolves the reviewer's display name from
 * `profiles` via a small cached query.
 *
 * Layer rule: this is a presentation-only component but it needs to look up
 * a profile name. To avoid duplicating React Query hooks for one tiny lookup
 * we do the query inline (cached 5 min). This is the only component-level
 * supabase call permitted by the Sprint 6B plan.
 */
import { useQuery } from '@tanstack/react-query';
import { Sparkles } from 'lucide-react';
import { format } from 'date-fns';
import { supabase } from '@/integrations/supabase/client';

export interface Pass3AttributionBadgeProps {
  reviewerUserId: string | null;
  reviewedAt: string | null;
}

interface ProfileRow {
  full_name: string | null;
  email: string | null;
}

export function Pass3AttributionBadge({
  reviewerUserId,
  reviewedAt,
}: Pass3AttributionBadgeProps) {
  const profileQuery = useQuery({
    queryKey: ['profile-display', reviewerUserId],
    enabled: !!reviewerUserId,
    staleTime: 5 * 60 * 1000,
    queryFn: async (): Promise<ProfileRow | null> => {
      const { data, error } = await supabase
        .from('profiles')
        .select('full_name, email')
        .eq('user_id', reviewerUserId!)
        .maybeSingle();
      if (error) return null;
      return (data as ProfileRow | null) ?? null;
    },
  });

  if (!reviewerUserId || !reviewedAt) return null;

  const displayName =
    profileQuery.data?.full_name?.trim() ||
    profileQuery.data?.email?.trim() ||
    'Platform Reviewer';

  let formattedDate = reviewedAt;
  try {
    formattedDate = format(new Date(reviewedAt), 'PPP');
  } catch {
    // keep ISO fallback
  }

  return (
    <div className="mt-3 flex items-center gap-2 rounded-md border bg-muted/40 px-3 py-2 text-xs text-muted-foreground">
      <Sparkles className="h-3.5 w-3.5 text-primary" aria-hidden="true" />
      <span>
        Generated by AI — Reviewed by{' '}
        <span className="font-medium text-foreground">{displayName}</span> on{' '}
        <span className="font-medium text-foreground">{formattedDate}</span>
      </span>
    </div>
  );
}

export default Pass3AttributionBadge;
