// CPA template content and platform doc content — extracted to reduce bundle size
export const CPA_TEMPLATES = [
  {
    document_code: "CPA_QUICK",
    document_name: "Challenge Participation Agreement (Quick)",
    applies_to_mode: "QUICK",
    template_content: [
      "CHALLENGE PARTICIPATION AGREEMENT (QUICK)",
      "Challenge: {{challenge_title}}",
      "Organization: {{seeker_org_name}}",
      "",
      "1. PARTICIPATION",
      "By enrolling, you agree to participate in good faith, submit original work, and comply with deadlines.",
      "",
      "2. CONFIDENTIALITY",
      "You will not share proprietary challenge details outside the platform.",
      "",
      "3. INTELLECTUAL PROPERTY",
      "{{ip_clause}}",
      "",
      "4. PRIZE AND PAYMENT",
      "Prize: {{currency}} {{prize_amount}}. Payment processed within 30 days of winner confirmation.",
      "",
      "5. GOVERNING LAW",
      "This agreement is governed by the laws of {{jurisdiction}}. Applicable regulations: {{governing_law}}.",
    ].join("\n"),
  },
  {
    document_code: "CPA_STRUCTURED",
    document_name: "Challenge Participation Agreement (Structured)",
    applies_to_mode: "STRUCTURED",
    template_content: [
      "CHALLENGE PARTICIPATION AGREEMENT (STRUCTURED)",
      "Challenge: {{challenge_title}}",
      "Organization: {{seeker_org_name}}",
      "",
      "1. PARTICIPATION RULES",
      "By enrolling, you agree to: (a) participate in good faith; (b) submit original work; (c) maintain confidentiality; (d) comply with all requirements and deadlines.",
      "",
      "2. CONFIDENTIALITY",
      "You shall not disclose proprietary information provided by the Organization including challenge details, business context, and technical specifications.",
      "",
      "3. INTELLECTUAL PROPERTY",
      "{{ip_clause}}",
      "You warrant your submission is original and you have authority to grant the above rights.",
      "",
      "4. PRIZE AND PAYMENT",
      "Prize: {{currency}} {{prize_amount}}. Payment within 30 days of winner confirmation.",
      "",
      "5. EVALUATION PROCESS",
      "Submissions evaluated using {{evaluation_method}} method against published criteria. Organization's decision is final subject to dispute resolution.",
      "",
      "6. DATA PROTECTION",
      "Applicable data protection: {{governing_law}}.",
      "",
      "7. CANCELLATION",
      "If cancelled post-enrollment, solvers who submitted receive compensation per Platform cancellation policy.",
      "",
      "{{anti_disintermediation}}",
      "",
      "8. GOVERNING LAW",
      "Governed by laws of {{jurisdiction}}.",
    ].join("\n"),
  },
  {
    document_code: "CPA_CONTROLLED",
    document_name: "Challenge Participation Agreement (Controlled)",
    applies_to_mode: "CONTROLLED",
    template_content: [
      "CHALLENGE PARTICIPATION AGREEMENT (CONTROLLED)",
      "Challenge: {{challenge_title}}",
      "Organization: {{seeker_org_name}}",
      "",
      "1. PARTICIPATION RULES",
      "By enrolling, you agree to: (a) participate in good faith; (b) submit original work not infringing third-party IP; (c) maintain strict confidentiality; (d) comply with all requirements, deadlines, and governance rules.",
      "",
      "2. CONFIDENTIALITY",
      "You shall not disclose, share, or use for any purpose other than challenge participation, any confidential information. This obligation survives challenge completion by 24 months.",
      "",
      "3. INTELLECTUAL PROPERTY",
      "{{ip_clause}}",
      "You warrant your submission is original and you have full authority to grant the above rights.",
      "",
      "4. PRIZE AND PAYMENT",
      "Prize: {{currency}} {{prize_amount}}.",
      "{{escrow_terms}}",
      "",
      "5. EVALUATION PROCESS",
      "Submissions evaluated using {{evaluation_method}} method. Evaluator and solver identities are blinded during evaluation.",
      "",
      "6. DATA PROTECTION AND REGULATORY COMPLIANCE",
      "Applicable regulations: {{governing_law}}.",
      "",
      "7. AUDIT RIGHTS",
      "The Platform reserves the right to audit the challenge process for compliance with fairness and integrity standards.",
      "",
      "8. CANCELLATION AND COMPENSATION",
      "If cancelled post-enrollment: (a) solvers with submitted solutions receive cancellation compensation; (b) remaining escrow returned after deducting Platform fees.",
      "",
      "9. INTEGRITY COMMITMENTS",
      "Organization commits to: (a) evaluate fairly without bias; (b) not use submissions without IP agreement; (c) disclose conflicts of interest.",
      "",
      "{{anti_disintermediation}}",
      "",
      "10. GOVERNING LAW",
      "Governed by laws of {{jurisdiction}}.",
    ].join("\n"),
  },
];

export const PLATFORM_DOC_CONTENT: Record<string, string> = {
  SPA: [
    "SOLVER PLATFORM AGREEMENT",
    "",
    "1. ACCEPTANCE: By creating an account, you accept these terms governing your use of the CogniBlend Platform.",
    "",
    "2. CONDUCT: You agree to participate professionally, submit original work, respect confidentiality, and comply with challenge rules.",
    "",
    "3. DATA PRIVACY: Your personal data is processed per our Privacy Policy. Submission data is shared only with the relevant seeking organization per challenge terms.",
    "",
    "4. INTELLECTUAL PROPERTY: Default IP terms are specified per challenge. You retain all IP until a specific IP agreement is executed for a winning submission.",
    "",
    "5. PAYMENTS: Prize payments are processed through the Platform within 30 days of winner confirmation and IP agreement execution.",
    "",
    "6. DISPUTE RESOLUTION: Disputes are resolved through Platform mediation, then binding arbitration.",
    "",
    "7. TERMINATION: Either party may terminate with 30 days notice. Active challenge participations must be honored.",
  ].join("\n"),

  SKPA: [
    "SEEKER PLATFORM AGREEMENT",
    "",
    "1. ACCEPTANCE: By enrolling your organization, you accept these terms governing challenge creation and management on the CogniBlend Platform.",
    "",
    "2. CHALLENGE OBLIGATIONS: You agree to provide accurate challenge descriptions, honor prize commitments, evaluate solutions fairly, and maintain solver confidentiality.",
    "",
    "3. FEES: Platform service fees are per your subscription plan. Escrow fees apply to Controlled governance challenges.",
    "",
    "4. DATA HANDLING: Solver personal data accessed through the Platform is subject to data protection laws. You may not contact solvers outside the Platform without consent.",
    "",
    "5. ESCROW: For Controlled governance, full prize deposit in escrow is required before challenge publication.",
    "",
    "6. LIABILITY: The Platform facilitates but does not guarantee challenge outcomes. The Platform is not liable for solver performance or solution quality.",
    "",
    "7. TERMINATION: Active challenges at termination must be honored including prize obligations.",
  ].join("\n"),

  PWA: [
    "PLATFORM WORKFORCE AGREEMENT",
    "",
    "1. ACCEPTANCE: By accepting a role assignment (Curator, Expert Reviewer, Legal Coordinator, or Finance Controller), you accept these terms.",
    "",
    "2. EVALUATION STANDARDS: You agree to evaluate challenges and solutions impartially, based solely on published criteria, and provide substantive documented feedback.",
    "",
    "3. CONFIDENTIALITY: All challenge details, solver submissions, and evaluation deliberations are strictly confidential. You may not share or use this information outside your Platform role.",
    "",
    "4. CONFLICT OF INTEREST: You must disclose any personal, financial, or professional relationship with seeking organizations or solvers that could affect impartiality.",
    "",
    "5. PERFORMANCE: You agree to meet evaluation SLAs. Repeated failure may result in role reassignment.",
    "",
    "6. COMPENSATION: Compensation for Platform workforce roles is per your individual agreement with the Platform.",
    "",
    "7. IMPARTIALITY: In blinded evaluations (Controlled governance), you must not attempt to identify solvers.",
  ].join("\n"),
};
