/**
 * ExtendedBriefDisplay — Read-only + editable renderer for extended_brief JSONB.
 * Shows Context & Background, Root Causes, Affected Stakeholders, Expected Outcomes,
 * Preferred Approach, Approaches Not of Interest as collapsible sub-sections.
 */

import { useState, useCallback } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { AiContentRenderer } from "@/components/ui/AiContentRenderer";
import { TextSectionEditor } from "@/components/cogniblend/curation/CurationSectionEditor";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import {
  ChevronDown,
  Pencil,
  Sparkles,
  Users,
  Target,
  AlertTriangle,
  Lightbulb,
  XCircle,
  FileText,
} from "lucide-react";
import { cn } from "@/lib/utils";
import type { Json } from "@/integrations/supabase/types";

interface ExtendedBriefData {
  context_background?: string;
  root_causes?: string;
  affected_stakeholders?: string[];
  current_deficiencies?: string;
  expected_outcomes?: string[];
  preferred_approach?: string;
  approaches_not_of_interest?: string;
  scoring_rubrics?: Array<{
    criterion_name: string;
    levels: Array<{ score: number; label: string; description: string }>;
  }>;
  effort_level?: string;
  reward_description?: string;
  phase_notes?: string;
  complexity_notes?: string;
}

interface ExtendedBriefDisplayProps {
  data: Json | null;
  onSave: (updatedBrief: ExtendedBriefData) => void;
  saving?: boolean;
  readOnly?: boolean;
}

const SUB_SECTIONS: Array<{
  key: keyof ExtendedBriefData;
  label: string;
  icon: React.ElementType;
  type: "text" | "array" | "rubrics";
}> = [
  { key: "context_background", label: "Context & Background", icon: FileText, type: "text" },
  { key: "root_causes", label: "Root Causes", icon: AlertTriangle, type: "text" },
  { key: "affected_stakeholders", label: "Affected Stakeholders", icon: Users, type: "array" },
  { key: "current_deficiencies", label: "Current Deficiencies", icon: XCircle, type: "text" },
  { key: "expected_outcomes", label: "Expected Outcomes", icon: Target, type: "array" },
  { key: "preferred_approach", label: "Preferred Approach", icon: Lightbulb, type: "text" },
  { key: "approaches_not_of_interest", label: "Approaches NOT of Interest", icon: XCircle, type: "text" },
];

function parseExtendedBrief(val: Json | null): ExtendedBriefData {
  if (!val) return {};
  if (typeof val === "string") {
    try { return JSON.parse(val); } catch { return {}; }
  }
  return val as unknown as ExtendedBriefData;
}

export default function ExtendedBriefDisplay({ data, onSave, saving, readOnly }: ExtendedBriefDisplayProps) {
  const brief = parseExtendedBrief(data);
  const [editingKey, setEditingKey] = useState<string | null>(null);

  const handleSaveField = useCallback((key: keyof ExtendedBriefData, value: string) => {
    const updated = { ...brief, [key]: value };
    onSave(updated);
    setEditingKey(null);
  }, [brief, onSave]);

  const hasAnyContent = SUB_SECTIONS.some((s) => {
    const val = brief[s.key];
    if (Array.isArray(val)) return val.length > 0;
    return typeof val === "string" && val.trim().length > 0;
  });

  if (!hasAnyContent && readOnly) {
    return (
      <div className="flex items-center gap-2 text-sm text-muted-foreground italic py-2">
        <Sparkles className="h-4 w-4" />
        Extended brief not yet generated by AI.
      </div>
    );
  }

  return (
    <div className="space-y-2">
      {SUB_SECTIONS.map((sub) => {
        const val = brief[sub.key];
        const hasContent = Array.isArray(val) ? val.length > 0 : typeof val === "string" && val.trim().length > 0;
        const isEditing = editingKey === sub.key;
        const Icon = sub.icon;

        return (
          <Collapsible key={sub.key} defaultOpen={hasContent}>
            <CollapsibleTrigger className="flex items-center gap-2 w-full text-left py-1.5 hover:bg-muted/30 rounded px-2 transition-colors group">
              <ChevronDown className="h-3.5 w-3.5 text-muted-foreground transition-transform group-data-[state=open]:rotate-0 group-data-[state=closed]:-rotate-90" />
              <Icon className="h-3.5 w-3.5 text-muted-foreground" />
              <span className="text-sm font-medium text-foreground">{sub.label}</span>
              {hasContent && (
                <Badge variant="secondary" className="text-[10px] ml-auto">
                  <Sparkles className="h-2.5 w-2.5 mr-0.5" />AI
                </Badge>
              )}
              {!hasContent && (
                <span className="text-[10px] text-muted-foreground ml-auto">Empty</span>
              )}
            </CollapsibleTrigger>
            <CollapsibleContent className="pl-8 pr-2 pb-2">
              {isEditing && sub.type === "text" ? (
                <TextSectionEditor
                  value={(val as string) ?? ""}
                  onSave={(v) => handleSaveField(sub.key, v)}
                  onCancel={() => setEditingKey(null)}
                  saving={saving}
                />
              ) : sub.type === "array" ? (
                <div className="space-y-1.5">
                  {Array.isArray(val) && val.length > 0 ? (
                    <ul className="space-y-1">
                      {(val as string[]).map((item, i) => (
                        <li key={i} className="flex items-start gap-2 text-sm text-foreground">
                          <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary text-[10px] font-semibold mt-0.5">
                            {i + 1}
                          </span>
                          {item}
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className="text-sm text-muted-foreground italic">Not defined</p>
                  )}
                </div>
              ) : (
                <>
                  {hasContent ? (
                    <AiContentRenderer content={val as string} compact />
                  ) : (
                    <p className="text-sm text-muted-foreground italic">Not defined</p>
                  )}
                  {!readOnly && !isEditing && sub.type === "text" && (
                    <Button
                      variant="ghost"
                      size="sm"
                      className="mt-2 text-xs"
                      onClick={() => setEditingKey(sub.key)}
                    >
                      <Pencil className="h-3 w-3 mr-1" />Edit
                    </Button>
                  )}
                </>
              )}
            </CollapsibleContent>
          </Collapsible>
        );
      })}

      {/* Effort Level + Complexity Notes + Phase Notes (compact) */}
      {(brief.effort_level || brief.complexity_notes || brief.phase_notes || brief.reward_description) && (
        <div className="border-t border-border/40 pt-3 mt-3 space-y-2">
          {brief.effort_level && (
            <div className="flex items-center gap-2">
              <span className="text-xs text-muted-foreground">Effort Level:</span>
              <Badge variant="outline" className="capitalize text-xs">{brief.effort_level}</Badge>
            </div>
          )}
          {brief.reward_description && (
            <div>
              <p className="text-xs text-muted-foreground mb-0.5">Reward Guidance</p>
              <p className="text-sm text-foreground">{brief.reward_description}</p>
            </div>
          )}
          {brief.phase_notes && (
            <div>
              <p className="text-xs text-muted-foreground mb-0.5">Phase Notes</p>
              <p className="text-sm text-foreground">{brief.phase_notes}</p>
            </div>
          )}
          {brief.complexity_notes && (
            <div>
              <p className="text-xs text-muted-foreground mb-0.5">Complexity Notes</p>
              <p className="text-sm text-foreground">{brief.complexity_notes}</p>
            </div>
          )}
        </div>
      )}

      {/* Scoring Rubrics */}
      {brief.scoring_rubrics && brief.scoring_rubrics.length > 0 && (
        <Collapsible>
          <CollapsibleTrigger className="flex items-center gap-2 w-full text-left py-1.5 hover:bg-muted/30 rounded px-2 transition-colors group">
            <ChevronDown className="h-3.5 w-3.5 text-muted-foreground transition-transform group-data-[state=open]:rotate-0 group-data-[state=closed]:-rotate-90" />
            <Target className="h-3.5 w-3.5 text-muted-foreground" />
            <span className="text-sm font-medium text-foreground">Scoring Rubrics</span>
            <Badge variant="secondary" className="text-[10px] ml-auto">
              {brief.scoring_rubrics.length} criteria
            </Badge>
          </CollapsibleTrigger>
          <CollapsibleContent className="pl-8 pr-2 pb-2">
            <div className="space-y-4">
              {brief.scoring_rubrics.map((rubric, ri) => (
                <div key={ri} className="space-y-1.5">
                  <p className="text-sm font-medium text-foreground">{rubric.criterion_name}</p>
                  <div className="relative w-full overflow-auto">
                    <table className="w-full text-xs">
                      <thead>
                        <tr className="border-b">
                          <th className="text-left py-1 pr-2 text-muted-foreground font-medium w-12">Score</th>
                          <th className="text-left py-1 pr-2 text-muted-foreground font-medium w-24">Label</th>
                          <th className="text-left py-1 text-muted-foreground font-medium">Description</th>
                        </tr>
                      </thead>
                      <tbody>
                        {rubric.levels.map((level, li) => (
                          <tr key={li} className="border-b border-border/30">
                            <td className="py-1 pr-2 font-mono font-medium text-primary">{level.score}</td>
                            <td className="py-1 pr-2 font-medium">{level.label}</td>
                            <td className="py-1 text-muted-foreground">{level.description}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              ))}
            </div>
          </CollapsibleContent>
        </Collapsible>
      )}
    </div>
  );
}
