
-- Add comprehensive list of world countries for testing
-- Only inserting countries that don't already exist (by code)
INSERT INTO countries (code, name, currency_symbol, date_format, number_format, is_active, is_ofac_restricted, display_order)
SELECT v.code, v.name, v.currency_symbol, v.date_format, v.number_format, true, false, v.display_order
FROM (VALUES
  ('AF', 'Afghanistan', '؋', 'DD/MM/YYYY', 'en-US', 100),
  ('AL', 'Albania', 'L', 'DD/MM/YYYY', 'en-US', 101),
  ('DZ', 'Algeria', 'د.ج', 'DD/MM/YYYY', 'fr-FR', 102),
  ('AD', 'Andorra', '€', 'DD/MM/YYYY', 'fr-FR', 103),
  ('AO', 'Angola', 'Kz', 'DD/MM/YYYY', 'pt-PT', 104),
  ('AG', 'Antigua and Barbuda', '$', 'DD/MM/YYYY', 'en-US', 105),
  ('AR', 'Argentina', '$', 'DD/MM/YYYY', 'es-AR', 106),
  ('AM', 'Armenia', '֏', 'DD/MM/YYYY', 'en-US', 107),
  ('AT', 'Austria', '€', 'DD.MM.YYYY', 'de-AT', 108),
  ('AZ', 'Azerbaijan', '₼', 'DD/MM/YYYY', 'en-US', 109),
  ('BS', 'Bahamas', '$', 'MM/DD/YYYY', 'en-US', 110),
  ('BH', 'Bahrain', '.د.ب', 'DD/MM/YYYY', 'en-US', 111),
  ('BD', 'Bangladesh', '৳', 'DD/MM/YYYY', 'en-US', 112),
  ('BB', 'Barbados', '$', 'DD/MM/YYYY', 'en-US', 113),
  ('BY', 'Belarus', 'Br', 'DD.MM.YYYY', 'en-US', 114),
  ('BE', 'Belgium', '€', 'DD/MM/YYYY', 'fr-BE', 115),
  ('BZ', 'Belize', '$', 'DD/MM/YYYY', 'en-US', 116),
  ('BJ', 'Benin', 'CFA', 'DD/MM/YYYY', 'fr-FR', 117),
  ('BT', 'Bhutan', 'Nu', 'DD/MM/YYYY', 'en-US', 118),
  ('BO', 'Bolivia', 'Bs', 'DD/MM/YYYY', 'es-BO', 119),
  ('BA', 'Bosnia and Herzegovina', 'KM', 'DD.MM.YYYY', 'en-US', 120),
  ('BW', 'Botswana', 'P', 'DD/MM/YYYY', 'en-US', 121),
  ('BN', 'Brunei', '$', 'DD/MM/YYYY', 'en-US', 122),
  ('BG', 'Bulgaria', 'лв', 'DD.MM.YYYY', 'en-US', 123),
  ('BF', 'Burkina Faso', 'CFA', 'DD/MM/YYYY', 'fr-FR', 124),
  ('BI', 'Burundi', 'FBu', 'DD/MM/YYYY', 'fr-FR', 125),
  ('KH', 'Cambodia', '៛', 'DD/MM/YYYY', 'en-US', 126),
  ('CM', 'Cameroon', 'CFA', 'DD/MM/YYYY', 'fr-FR', 127),
  ('CV', 'Cape Verde', '$', 'DD/MM/YYYY', 'pt-PT', 128),
  ('CF', 'Central African Republic', 'CFA', 'DD/MM/YYYY', 'fr-FR', 129),
  ('TD', 'Chad', 'CFA', 'DD/MM/YYYY', 'fr-FR', 130),
  ('CL', 'Chile', '$', 'DD/MM/YYYY', 'es-CL', 131),
  ('CN', 'China', '¥', 'YYYY/MM/DD', 'zh-CN', 132),
  ('CO', 'Colombia', '$', 'DD/MM/YYYY', 'es-CO', 133),
  ('KM', 'Comoros', 'CF', 'DD/MM/YYYY', 'fr-FR', 134),
  ('CG', 'Congo', 'CFA', 'DD/MM/YYYY', 'fr-FR', 135),
  ('CD', 'Congo (DRC)', 'FC', 'DD/MM/YYYY', 'fr-FR', 136),
  ('CR', 'Costa Rica', '₡', 'DD/MM/YYYY', 'es-CR', 137),
  ('CI', 'Côte d''Ivoire', 'CFA', 'DD/MM/YYYY', 'fr-FR', 138),
  ('HR', 'Croatia', '€', 'DD.MM.YYYY', 'hr-HR', 139),
  ('CY', 'Cyprus', '€', 'DD/MM/YYYY', 'en-US', 140),
  ('CZ', 'Czech Republic', 'Kč', 'DD.MM.YYYY', 'cs-CZ', 141),
  ('DK', 'Denmark', 'kr', 'DD-MM-YYYY', 'da-DK', 142),
  ('DJ', 'Djibouti', 'Fdj', 'DD/MM/YYYY', 'fr-FR', 143),
  ('DM', 'Dominica', '$', 'DD/MM/YYYY', 'en-US', 144),
  ('DO', 'Dominican Republic', '$', 'DD/MM/YYYY', 'es-DO', 145),
  ('EC', 'Ecuador', '$', 'DD/MM/YYYY', 'es-EC', 146),
  ('EG', 'Egypt', '£', 'DD/MM/YYYY', 'ar-EG', 147),
  ('SV', 'El Salvador', '$', 'DD/MM/YYYY', 'es-SV', 148),
  ('GQ', 'Equatorial Guinea', 'CFA', 'DD/MM/YYYY', 'es-GQ', 149),
  ('ER', 'Eritrea', 'Nfk', 'DD/MM/YYYY', 'en-US', 150),
  ('EE', 'Estonia', '€', 'DD.MM.YYYY', 'et-EE', 151),
  ('SZ', 'Eswatini', 'E', 'DD/MM/YYYY', 'en-US', 152),
  ('ET', 'Ethiopia', 'Br', 'DD/MM/YYYY', 'en-US', 153),
  ('FJ', 'Fiji', '$', 'DD/MM/YYYY', 'en-US', 154),
  ('FI', 'Finland', '€', 'DD.MM.YYYY', 'fi-FI', 155),
  ('GA', 'Gabon', 'CFA', 'DD/MM/YYYY', 'fr-FR', 156),
  ('GM', 'Gambia', 'D', 'DD/MM/YYYY', 'en-US', 157),
  ('GE', 'Georgia', '₾', 'DD.MM.YYYY', 'en-US', 158),
  ('GH', 'Ghana', '₵', 'DD/MM/YYYY', 'en-US', 159),
  ('GR', 'Greece', '€', 'DD/MM/YYYY', 'el-GR', 160),
  ('GD', 'Grenada', '$', 'DD/MM/YYYY', 'en-US', 161),
  ('GT', 'Guatemala', 'Q', 'DD/MM/YYYY', 'es-GT', 162),
  ('GN', 'Guinea', 'FG', 'DD/MM/YYYY', 'fr-FR', 163),
  ('GW', 'Guinea-Bissau', 'CFA', 'DD/MM/YYYY', 'pt-PT', 164),
  ('GY', 'Guyana', '$', 'DD/MM/YYYY', 'en-US', 165),
  ('HT', 'Haiti', 'G', 'DD/MM/YYYY', 'fr-FR', 166),
  ('HN', 'Honduras', 'L', 'DD/MM/YYYY', 'es-HN', 167),
  ('HK', 'Hong Kong', '$', 'DD/MM/YYYY', 'en-HK', 168),
  ('HU', 'Hungary', 'Ft', 'YYYY.MM.DD', 'hu-HU', 169),
  ('IS', 'Iceland', 'kr', 'DD.MM.YYYY', 'is-IS', 170),
  ('ID', 'Indonesia', 'Rp', 'DD/MM/YYYY', 'id-ID', 171),
  ('IQ', 'Iraq', 'ع.د', 'DD/MM/YYYY', 'ar-IQ', 172),
  ('IT', 'Italy', '€', 'DD/MM/YYYY', 'it-IT', 173),
  ('JM', 'Jamaica', '$', 'DD/MM/YYYY', 'en-US', 174),
  ('JO', 'Jordan', 'د.ا', 'DD/MM/YYYY', 'ar-JO', 175),
  ('KZ', 'Kazakhstan', '₸', 'DD.MM.YYYY', 'en-US', 176),
  ('KE', 'Kenya', 'KSh', 'DD/MM/YYYY', 'en-US', 177),
  ('KI', 'Kiribati', '$', 'DD/MM/YYYY', 'en-US', 178),
  ('KW', 'Kuwait', 'د.ك', 'DD/MM/YYYY', 'ar-KW', 179),
  ('KG', 'Kyrgyzstan', 'сом', 'DD.MM.YYYY', 'en-US', 180),
  ('LA', 'Laos', '₭', 'DD/MM/YYYY', 'en-US', 181),
  ('LV', 'Latvia', '€', 'DD.MM.YYYY', 'lv-LV', 182),
  ('LB', 'Lebanon', 'ل.ل', 'DD/MM/YYYY', 'ar-LB', 183),
  ('LS', 'Lesotho', 'L', 'DD/MM/YYYY', 'en-US', 184),
  ('LR', 'Liberia', '$', 'DD/MM/YYYY', 'en-US', 185),
  ('LY', 'Libya', 'ل.د', 'DD/MM/YYYY', 'ar-LY', 186),
  ('LI', 'Liechtenstein', 'CHF', 'DD.MM.YYYY', 'de-LI', 187),
  ('LT', 'Lithuania', '€', 'YYYY-MM-DD', 'lt-LT', 188),
  ('LU', 'Luxembourg', '€', 'DD/MM/YYYY', 'fr-LU', 189),
  ('MO', 'Macau', 'MOP$', 'DD/MM/YYYY', 'zh-MO', 190),
  ('MG', 'Madagascar', 'Ar', 'DD/MM/YYYY', 'fr-FR', 191),
  ('MW', 'Malawi', 'MK', 'DD/MM/YYYY', 'en-US', 192),
  ('MY', 'Malaysia', 'RM', 'DD/MM/YYYY', 'ms-MY', 193),
  ('MV', 'Maldives', 'Rf', 'DD/MM/YYYY', 'en-US', 194),
  ('ML', 'Mali', 'CFA', 'DD/MM/YYYY', 'fr-FR', 195),
  ('MT', 'Malta', '€', 'DD/MM/YYYY', 'en-MT', 196),
  ('MH', 'Marshall Islands', '$', 'MM/DD/YYYY', 'en-US', 197),
  ('MR', 'Mauritania', 'UM', 'DD/MM/YYYY', 'ar-MR', 198),
  ('MU', 'Mauritius', '₨', 'DD/MM/YYYY', 'en-US', 199),
  ('FM', 'Micronesia', '$', 'MM/DD/YYYY', 'en-US', 200),
  ('MD', 'Moldova', 'L', 'DD.MM.YYYY', 'en-US', 201),
  ('MC', 'Monaco', '€', 'DD/MM/YYYY', 'fr-MC', 202),
  ('MN', 'Mongolia', '₮', 'YYYY.MM.DD', 'en-US', 203),
  ('ME', 'Montenegro', '€', 'DD.MM.YYYY', 'en-US', 204),
  ('MA', 'Morocco', 'د.م.', 'DD/MM/YYYY', 'fr-MA', 205),
  ('MZ', 'Mozambique', 'MT', 'DD/MM/YYYY', 'pt-MZ', 206),
  ('MM', 'Myanmar', 'K', 'DD/MM/YYYY', 'en-US', 207),
  ('NA', 'Namibia', '$', 'DD/MM/YYYY', 'en-US', 208),
  ('NR', 'Nauru', '$', 'DD/MM/YYYY', 'en-US', 209),
  ('NP', 'Nepal', '₨', 'DD/MM/YYYY', 'en-US', 210),
  ('NI', 'Nicaragua', 'C$', 'DD/MM/YYYY', 'es-NI', 211),
  ('NE', 'Niger', 'CFA', 'DD/MM/YYYY', 'fr-FR', 212),
  ('NG', 'Nigeria', '₦', 'DD/MM/YYYY', 'en-NG', 213),
  ('MK', 'North Macedonia', 'ден', 'DD.MM.YYYY', 'en-US', 214),
  ('NO', 'Norway', 'kr', 'DD.MM.YYYY', 'nb-NO', 215),
  ('OM', 'Oman', 'ر.ع.', 'DD/MM/YYYY', 'ar-OM', 216),
  ('PK', 'Pakistan', '₨', 'DD/MM/YYYY', 'en-PK', 217),
  ('PW', 'Palau', '$', 'MM/DD/YYYY', 'en-US', 218),
  ('PS', 'Palestine', '₪', 'DD/MM/YYYY', 'ar-PS', 219),
  ('PA', 'Panama', 'B/.', 'DD/MM/YYYY', 'es-PA', 220),
  ('PG', 'Papua New Guinea', 'K', 'DD/MM/YYYY', 'en-US', 221),
  ('PY', 'Paraguay', '₲', 'DD/MM/YYYY', 'es-PY', 222),
  ('PE', 'Peru', 'S/', 'DD/MM/YYYY', 'es-PE', 223),
  ('PH', 'Philippines', '₱', 'MM/DD/YYYY', 'en-PH', 224),
  ('PL', 'Poland', 'zł', 'DD.MM.YYYY', 'pl-PL', 225),
  ('PT', 'Portugal', '€', 'DD/MM/YYYY', 'pt-PT', 226),
  ('QA', 'Qatar', 'ر.ق', 'DD/MM/YYYY', 'ar-QA', 227),
  ('RO', 'Romania', 'lei', 'DD.MM.YYYY', 'ro-RO', 228),
  ('RU', 'Russia', '₽', 'DD.MM.YYYY', 'ru-RU', 229),
  ('RW', 'Rwanda', 'RF', 'DD/MM/YYYY', 'en-US', 230),
  ('KN', 'Saint Kitts and Nevis', '$', 'DD/MM/YYYY', 'en-US', 231),
  ('LC', 'Saint Lucia', '$', 'DD/MM/YYYY', 'en-US', 232),
  ('VC', 'Saint Vincent', '$', 'DD/MM/YYYY', 'en-US', 233),
  ('WS', 'Samoa', 'T', 'DD/MM/YYYY', 'en-US', 234),
  ('SM', 'San Marino', '€', 'DD/MM/YYYY', 'it-IT', 235),
  ('ST', 'São Tomé and Príncipe', 'Db', 'DD/MM/YYYY', 'pt-PT', 236),
  ('SA', 'Saudi Arabia', 'ر.س', 'DD/MM/YYYY', 'ar-SA', 237),
  ('SN', 'Senegal', 'CFA', 'DD/MM/YYYY', 'fr-FR', 238),
  ('RS', 'Serbia', 'din', 'DD.MM.YYYY', 'sr-RS', 239),
  ('SC', 'Seychelles', '₨', 'DD/MM/YYYY', 'en-US', 240),
  ('SL', 'Sierra Leone', 'Le', 'DD/MM/YYYY', 'en-US', 241),
  ('SK', 'Slovakia', '€', 'DD.MM.YYYY', 'sk-SK', 242),
  ('SI', 'Slovenia', '€', 'DD.MM.YYYY', 'sl-SI', 243),
  ('SB', 'Solomon Islands', '$', 'DD/MM/YYYY', 'en-US', 244),
  ('SO', 'Somalia', 'Sh', 'DD/MM/YYYY', 'en-US', 245),
  ('SS', 'South Sudan', '£', 'DD/MM/YYYY', 'en-US', 246),
  ('ES', 'Spain', '€', 'DD/MM/YYYY', 'es-ES', 247),
  ('LK', 'Sri Lanka', '₨', 'DD/MM/YYYY', 'en-US', 248),
  ('SR', 'Suriname', '$', 'DD/MM/YYYY', 'nl-SR', 249),
  ('TW', 'Taiwan', 'NT$', 'YYYY/MM/DD', 'zh-TW', 250),
  ('TJ', 'Tajikistan', 'SM', 'DD.MM.YYYY', 'en-US', 251),
  ('TZ', 'Tanzania', 'TSh', 'DD/MM/YYYY', 'en-US', 252),
  ('TH', 'Thailand', '฿', 'DD/MM/YYYY', 'th-TH', 253),
  ('TL', 'Timor-Leste', '$', 'DD/MM/YYYY', 'pt-PT', 254),
  ('TG', 'Togo', 'CFA', 'DD/MM/YYYY', 'fr-FR', 255),
  ('TO', 'Tonga', 'T$', 'DD/MM/YYYY', 'en-US', 256),
  ('TT', 'Trinidad and Tobago', '$', 'DD/MM/YYYY', 'en-US', 257),
  ('TN', 'Tunisia', 'د.ت', 'DD/MM/YYYY', 'fr-TN', 258),
  ('TR', 'Turkey', '₺', 'DD.MM.YYYY', 'tr-TR', 259),
  ('TM', 'Turkmenistan', 'T', 'DD.MM.YYYY', 'en-US', 260),
  ('TV', 'Tuvalu', '$', 'DD/MM/YYYY', 'en-US', 261),
  ('UG', 'Uganda', 'USh', 'DD/MM/YYYY', 'en-US', 262),
  ('UA', 'Ukraine', '₴', 'DD.MM.YYYY', 'uk-UA', 263),
  ('UY', 'Uruguay', '$', 'DD/MM/YYYY', 'es-UY', 264),
  ('UZ', 'Uzbekistan', 'сўм', 'DD.MM.YYYY', 'en-US', 265),
  ('VU', 'Vanuatu', 'VT', 'DD/MM/YYYY', 'en-US', 266),
  ('VA', 'Vatican City', '€', 'DD/MM/YYYY', 'it-VA', 267),
  ('VE', 'Venezuela', 'Bs', 'DD/MM/YYYY', 'es-VE', 268),
  ('VN', 'Vietnam', '₫', 'DD/MM/YYYY', 'vi-VN', 269),
  ('YE', 'Yemen', '﷼', 'DD/MM/YYYY', 'ar-YE', 270),
  ('ZM', 'Zambia', 'ZK', 'DD/MM/YYYY', 'en-US', 271),
  ('ZW', 'Zimbabwe', '$', 'DD/MM/YYYY', 'en-US', 272)
) AS v(code, name, currency_symbol, date_format, number_format, display_order)
WHERE NOT EXISTS (
  SELECT 1 FROM countries c WHERE c.code = v.code
);
