
-- ============================================================
-- Gap 1: Update 5 key section exemplars to Principal-grade
-- ============================================================

UPDATE public.ai_review_section_config
SET example_good = E'A logistics operator managing 12 regional distribution centres loses approximately $2.3M annually to manual inventory reconciliation errors between their warehouse management system (SAP EWM) and ERP (SAP S/4HANA). Despite two previous improvement initiatives (2022 RPA pilot, 2023 middleware upgrade), the discrepancy rate remains at 47 incidents per week, each requiring 30–90 minutes of manual investigation by warehouse supervisors.\n\nRoot cause analysis (Ishikawa) identifies three failure modes: (1) batch-to-real-time timing mismatches causing 62% of discrepancies, (2) master data drift between systems accounting for 23%, and (3) exception-handling logic gaps covering the remaining 15%. Industry benchmarks (Gartner Supply Chain Top 25, 2024) indicate that top-quartile operators achieve <5 incidents/week at comparable scale.\n\nThe financial impact decomposes as: labour cost of investigation ($1.4M), downstream fulfilment delays ($0.6M), and inventory write-offs from unresolved discrepancies ($0.3M). Without intervention, planned expansion to 18 centres by Q3 2026 will scale the problem to an estimated $3.8M annually.',
    updated_at = now()
WHERE role_context = 'curation' AND section_key = 'problem_statement';

UPDATE public.ai_review_section_config
SET example_good = E'IN SCOPE:\n• Data synchronisation layer between SAP EWM and SAP S/4HANA, covering all 12 distribution centres and 3 data domains (inventory movements, master data, exception events)\n• Real-time event-driven architecture replacing current batch processing (target: <30 second propagation latency per MuleSoft Anypoint benchmarks)\n• Automated exception detection engine covering the three identified failure modes with configurable thresholds\n• Alerting and escalation workflow integrated with existing ServiceNow ITSM instance\n\nOUT OF SCOPE:\n• Changes to SAP EWM or S/4HANA core configuration, module upgrades, or licensing\n• Supplier-facing EDI interfaces and B2B gateway integrations\n• Mobile hardware (RF scanners, handheld devices) — firmware and OS are managed under a separate programme\n• Any warehouse process outside the inventory reconciliation workflow (e.g., putaway optimisation, slotting)\n• Data migration or historical data cleansing — solution operates on forward-flowing transactions only\n\nBOUNDARY ASSUMPTIONS:\n• Solution must operate within the existing network topology (hub-and-spoke VPN between DCs and central data centre)\n• Authentication via existing Azure AD tenant — no new identity provider\n• Performance SLA: sustain 500 transactions/minute during peak (Black Friday baseline from 2024)',
    updated_at = now()
WHERE role_context = 'curation' AND section_key = 'scope';

UPDATE public.ai_review_section_config
SET example_good = E'D1: Working middleware integration package with automated deployment script\n— Acceptance: IT Architect can deploy to staging environment without vendor support within 4 hours; all 12 DC connections established and health-checked green.\n— Standard: Must pass integration test suite (≥95% of 200+ test cases) against production-mirrored staging data.\n\nD2: Technical documentation package (minimum 25 pages)\n— Acceptance: Covers all configuration parameters, error codes, escalation procedures, and capacity planning guidelines.\n— Standard: Reviewed against IEEE 1063 documentation quality checklist; scores ≥80% on completeness assessment.\n— Cross-reference: Must align with scope boundary assumptions (network topology, Azure AD, performance SLA).\n\nD3: Exception detection ruleset with self-tuning capability\n— Acceptance: Passes automated regression test against 6-month historical transaction log with ≥95% detection coverage and <2% false positive rate.\n— Standard: Rules engine must be configurable by business users (warehouse supervisors) without code changes.\n— Benchmark: Detection latency <5 seconds per exception event (ref: Gartner real-time analytics benchmark).\n\nD4: Runbook and knowledge transfer package\n— Acceptance: Operations team completes 3 simulated incident scenarios without vendor assistance.\n— Standard: Mean time to resolution for simulated incidents <15 minutes.',
    updated_at = now()
WHERE role_context = 'curation' AND section_key = 'deliverables';

UPDATE public.ai_review_section_config
SET example_good = E'SCORING METHOD: Weighted multi-criteria, single panel (IT Architect + AP Manager + Warehouse Operations Lead)\n\n(1) Technical Performance — 40%\n— Method: Automated integration test suite against production-mirrored staging environment\n— Scorer: IT Architect\n— Benchmark: ≥95% test pass rate, <30s propagation latency, sustains 500 txn/min\n— Evidence: Test execution report with pass/fail counts, latency percentiles (p50, p95, p99)\n\n(2) Documentation Quality — 20%\n— Method: IEEE 1063 completeness checklist + deployment walkthrough\n— Scorer: IT Manager\n— Benchmark: ≥80% checklist score, successful unassisted staging deployment within 4 hours\n— Evidence: Checklist scorecard, deployment log with timestamps\n\n(3) Exception Detection Accuracy — 25%\n— Method: Historical log regression test (6-month dataset, ~14,000 transactions)\n— Scorer: AP Manager + Warehouse Operations Lead (joint)\n— Benchmark: ≥95% detection coverage, <2% false positive rate, <5s detection latency\n— Evidence: Confusion matrix, false positive analysis report\n\n(4) Operability & Knowledge Transfer — 15%\n— Method: 3 simulated incident scenarios executed by operations team without vendor support\n— Scorer: Warehouse Operations Lead\n— Benchmark: All scenarios resolved, MTTR <15 minutes average\n— Evidence: Scenario execution logs, MTTR measurements\n\nTotal: 100%. Minimum qualifying score: 60% overall with no single criterion below 40%.\nCross-reference: Criteria map directly to D1–D4 deliverables and scope performance SLA.',
    updated_at = now()
WHERE role_context = 'curation' AND section_key = 'evaluation_criteria';

UPDATE public.ai_review_section_config
SET example_good = E'PRIZE STRUCTURE:\n• First Prize: $75,000 USD — awarded to the highest-scoring submission meeting all acceptance criteria\n• Second Prize: $25,000 USD — awarded to the second-highest-scoring qualifying submission\n• Total Prize Pool: $100,000 USD\n\nPAYMENT TERMS:\n• Payment within 30 calendar days of IP transfer documentation execution\n• Wire transfer to solver-designated bank account (international transfers supported)\n• Prize conditional on passing all acceptance tests defined in D1–D4 deliverables section\n• No partial payments for incomplete submissions\n\nADDITIONAL INCENTIVES:\n• Both winning solvers receive a platform-verified case study publication (estimated value: enhanced solver profile visibility)\n• First-prize winner offered first-right-of-refusal for Phase 2 production deployment engagement (separate commercial terms)\n\nBUDGET CONTEXT:\n• Prize pool represents ~4.3% of the $2.3M annual cost of the problem — ROI-positive if the solution achieves even 50% of target improvement\n• Benchmark: Gartner innovation challenge benchmarks (2024) indicate median prize pools of $50K–$150K for middleware integration challenges at this complexity level\n\nNON-AWARD SCENARIO:\n• If no submission meets the minimum qualifying score (60% overall, no criterion below 40%), the prize pool is not awarded. Seeker may elect to extend the submission deadline by up to 30 days.',
    updated_at = now()
WHERE role_context = 'curation' AND section_key = 'reward_structure';

-- ============================================================
-- Gap 3: Seed ai_review_frameworks with consulting frameworks
-- ============================================================

INSERT INTO public.ai_review_frameworks (framework_name, applicability_condition, how_to_apply, typical_pitfalls, when_not_to_use, domain_tags, is_active) VALUES
-- STRATEGY FRAMEWORKS (1-15)
('Porter''s Five Forces', 'When analysing competitive dynamics, market entry barriers, or supplier/buyer power in an industry context', 'Map each force (rivalry, new entrants, substitutes, buyer power, supplier power) to the challenge domain. Quantify where possible using market data.', 'Treating forces as static; ignoring digital disruption as a substitute threat; conflating buyer and end-consumer power', 'Internal operational problems with no competitive dimension; pure technology implementation challenges', '["strategy","market_analysis","competitive_intelligence"]', true),
('McKinsey 7S Framework', 'When assessing organisational readiness for change or diagnosing alignment gaps between strategy and execution', 'Evaluate all 7 elements (Strategy, Structure, Systems, Shared Values, Skills, Style, Staff) and identify misalignments relevant to the challenge.', 'Focusing only on hard elements (strategy/structure/systems) while ignoring soft elements; superficial coverage without actionable findings', 'Pure technology challenges with no organisational change component; early-stage ideation', '["strategy","change_management","organisational_design"]', true),
('SWOT Analysis', 'When providing a structured overview of internal strengths/weaknesses and external opportunities/threats', 'Populate each quadrant with specific, evidence-based factors. Cross-reference SO/ST/WO/WT combinations for strategic options.', 'Generic statements lacking specificity; listing too many factors without prioritisation; confusing internal and external factors', 'Detailed operational planning; quantitative financial analysis; when more rigorous frameworks (e.g., PESTEL + Five Forces) are warranted', '["strategy","planning","assessment"]', true),
('PESTEL Analysis', 'When evaluating macro-environmental factors affecting an industry, market, or regulatory landscape', 'Systematically assess Political, Economic, Social, Technological, Environmental, and Legal factors relevant to the challenge geography and industry.', 'Listing generic factors not specific to the challenge; ignoring interdependencies between factors; failing to prioritise by impact', 'Internal process optimisation; technology architecture decisions; challenges with no external environmental sensitivity', '["strategy","market_analysis","regulatory"]', true),
('Ansoff Growth Matrix', 'When evaluating growth strategy options: market penetration, market development, product development, or diversification', 'Position the challenge within the appropriate quadrant and assess risk/reward trade-offs. Reference market data for sizing.', 'Defaulting to diversification without exhausting lower-risk options; ignoring capability gaps required for new quadrants', 'Cost reduction challenges; operational efficiency; challenges not related to growth or market expansion', '["strategy","growth","market_analysis"]', true),
('Blue Ocean Strategy', 'When the challenge involves creating new market space or differentiating beyond existing competitive boundaries', 'Apply the Four Actions Framework (Eliminate, Reduce, Raise, Create) to identify value innovation opportunities.', 'Ignoring execution feasibility; underestimating incumbent response; confusing cost cutting with value innovation', 'Mature markets requiring incremental improvement; regulatory compliance challenges; operational efficiency', '["strategy","innovation","market_analysis"]', true),
('BCG Growth-Share Matrix', 'When evaluating portfolio allocation across multiple products, business units, or solution components', 'Classify elements as Stars, Cash Cows, Question Marks, or Dogs based on market growth rate and relative market share.', 'Using outdated market data; applying to single-product businesses; ignoring strategic interdependencies between units', 'Single-solution challenges; technology architecture; challenges without portfolio or investment allocation decisions', '["strategy","portfolio","investment"]', true),
('Value Chain Analysis (Porter)', 'When identifying where value is created or lost in an organisation''s activities, or when optimising cost structures', 'Map primary activities (inbound logistics through service) and support activities. Identify cost drivers and differentiation sources.', 'Stopping at activity mapping without linking to competitive advantage; ignoring linkages between activities; outdated for digital-first businesses', 'Pure strategy formulation without operational detail; challenges focused on external market dynamics', '["strategy","operations","cost_optimisation"]', true),
('GE-McKinsey Nine-Box Matrix', 'When prioritising investments across business units or market segments based on industry attractiveness and competitive strength', 'Score each dimension using weighted criteria specific to the challenge context. Plot units and derive invest/hold/divest recommendations.', 'Subjective scoring without data backing; using generic rather than context-specific criteria; ignoring strategic synergies', 'Single-product decisions; technology selection; challenges without portfolio or resource allocation scope', '["strategy","portfolio","investment"]', true),
('Scenario Planning', 'When future uncertainty is high and the challenge requires robust strategies across multiple possible futures', 'Identify 2-3 critical uncertainties, construct distinct scenarios, stress-test the proposed solution against each scenario.', 'Creating too many scenarios; making scenarios too similar; failing to identify actionable implications for each scenario', 'Short-term operational challenges; well-defined problems with low uncertainty; compliance-driven implementations', '["strategy","risk","planning"]', true),

-- OPERATIONS & PROCESS FRAMEWORKS (11-25)
('Lean Six Sigma (DMAIC)', 'When the challenge involves process improvement, waste reduction, or quality enhancement with measurable defect rates', 'Apply Define-Measure-Analyse-Improve-Control phases. Quantify current sigma level, identify root causes, propose improvements with projected sigma improvement.', 'Skipping the Measure phase; applying to creative/innovation challenges; over-engineering control mechanisms for simple processes', 'R&D and innovation challenges; greenfield implementations; challenges where the process does not yet exist', '["operations","quality","process_improvement"]', true),
('Theory of Constraints (TOC)', 'When a system has an identifiable bottleneck limiting throughput, or when optimising flow through a process', 'Identify the constraint, exploit it, subordinate everything else to it, elevate the constraint, repeat. Quantify throughput impact.', 'Trying to optimise everything simultaneously; misidentifying the true constraint; ignoring that elevating one constraint creates another', 'Challenges without clear throughput or flow dynamics; pure strategy or market analysis problems', '["operations","process_improvement","capacity_planning"]', true),
('Business Process Reengineering (BPR)', 'When incremental improvement is insufficient and the challenge calls for fundamental process redesign', 'Map current state (as-is), design future state (to-be) from first principles, quantify the gap, define transition plan.', 'Underestimating change management; redesigning without stakeholder input; assuming technology alone solves process problems', 'Challenges requiring only incremental improvement; stable processes performing near benchmark; cultural or people-focused challenges', '["operations","transformation","process_improvement"]', true),
('SIPOC Diagram', 'When defining process boundaries, identifying key stakeholders, or establishing scope for process improvement initiatives', 'Map Suppliers, Inputs, Process steps, Outputs, and Customers for the relevant workflow. Use to validate scope boundaries.', 'Going too granular too early; missing indirect stakeholders; confusing SIPOC with detailed process mapping', 'Challenges not related to process definition; pure technology architecture; strategic planning without operational scope', '["operations","process_improvement","scoping"]', true),
('RACI Matrix', 'When clarifying roles, responsibilities, and decision rights across stakeholders in the challenge execution', 'Assign Responsible, Accountable, Consulted, Informed roles for each key activity or deliverable. Ensure single accountability.', 'Multiple Accountable parties per activity; confusing Responsible with Accountable; creating overly granular matrices', 'Challenges with a single decision-maker; early ideation; pure technical implementation with clear ownership', '["operations","governance","project_management"]', true),
('Kanban Framework', 'When managing workflow visualisation, WIP limits, and continuous delivery in ongoing processes', 'Visualise the workflow, set WIP limits, manage flow, make policies explicit, implement feedback loops, improve collaboratively.', 'Setting WIP limits too high (defeating the purpose); not respecting limits when pressure increases; using Kanban for waterfall with stickies', 'Challenges requiring big-bang delivery; one-time implementations; challenges without ongoing workflow characteristics', '["operations","agile","project_management"]', true),
('OKR Framework (Objectives and Key Results)', 'When defining measurable outcomes for challenge success or aligning team efforts around quantifiable targets', 'Define 3-5 ambitious Objectives with 2-4 measurable Key Results each. Key Results should be quantitative and time-bound.', 'Setting too many OKRs; making Key Results binary (done/not done) instead of measurable; confusing outputs with outcomes', 'Challenges requiring detailed task management; compliance-driven work with prescribed outputs; challenges without measurable outcomes', '["operations","performance","goal_setting"]', true),
('ITIL v4 Service Management', 'When the challenge involves IT service design, delivery, or continuous improvement within an established ITSM framework', 'Apply relevant ITIL practices (incident, problem, change, service level management) to structure the solution approach.', 'Implementing all ITIL practices regardless of relevance; treating ITIL as rigid methodology rather than adaptable framework; ignoring organisational context', 'Greenfield technology development; non-IT operational challenges; early-stage startups without service management maturity', '["operations","it_service","governance"]', true),

-- TECHNOLOGY & ARCHITECTURE FRAMEWORKS (19-35)
('TOGAF (The Open Group Architecture Framework)', 'When the challenge involves enterprise architecture planning, technology landscape assessment, or architecture governance', 'Apply the Architecture Development Method (ADM) phases relevant to the challenge. Reference architecture building blocks and standards.', 'Applying full ADM to small projects; producing excessive documentation; ignoring business architecture in favour of technology architecture', 'Small single-system implementations; non-technology challenges; challenges requiring rapid prototyping over architecture rigour', '["technology","architecture","enterprise"]', true),
('Zachman Framework', 'When establishing a comprehensive enterprise architecture taxonomy or ensuring coverage across architectural dimensions', 'Map challenge elements across the What/How/Where/Who/When/Why dimensions at the appropriate abstraction level.', 'Trying to fill every cell; treating it as a methodology rather than a taxonomy; creating complexity without insight', 'Focused technology implementations; operational improvements; challenges not requiring architectural classification', '["technology","architecture","enterprise"]', true),
('COBIT 2019', 'When IT governance, risk management, and compliance are central to the challenge, particularly in regulated industries', 'Align relevant COBIT governance and management objectives to the challenge requirements. Map controls to risk areas.', 'Implementing all 40 objectives regardless of relevance; treating COBIT as a technical framework rather than governance; ignoring organisational capability maturity', 'Startups without governance requirements; pure innovation challenges; non-regulated technology implementations', '["technology","governance","risk","compliance"]', true),
('SAFe (Scaled Agile Framework)', 'When the challenge involves large-scale agile transformation or coordinating multiple agile teams toward a common solution', 'Apply relevant SAFe configurations (Essential, Large Solution, Portfolio) based on challenge scale. Define ARTs and value streams.', 'Implementing full SAFe for small teams; ignoring Lean-Agile principles while adopting ceremonies; treating SAFe as prescriptive rather than adaptable', 'Small team projects; challenges not requiring cross-team coordination; organisations without existing agile maturity', '["technology","agile","transformation","project_management"]', true),
('Microservices Architecture Patterns', 'When evaluating or designing distributed system architectures, particularly for scalability, resilience, or team autonomy', 'Apply relevant patterns (API Gateway, Circuit Breaker, Saga, CQRS, Event Sourcing) to the challenge architecture. Justify trade-offs.', 'Defaulting to microservices for simple applications; ignoring operational complexity; distributed monolith anti-pattern', 'Monolithic applications with low complexity; early-stage MVPs; challenges where simplicity outweighs scalability needs', '["technology","architecture","software_engineering"]', true),
('DevOps Maturity Model', 'When assessing or improving software delivery capabilities, deployment frequency, and operational excellence', 'Evaluate current maturity across key dimensions (CI/CD, monitoring, IaC, collaboration, security). Identify target state and gap.', 'Focusing on tools over culture; measuring maturity without linking to business outcomes; skipping foundational practices', 'Challenges not involving software delivery; hardware or physical systems; non-technology operational improvements', '["technology","devops","operations"]', true),
('Cloud Adoption Framework (CAF)', 'When planning cloud migration, evaluating cloud-readiness, or designing cloud-native architectures', 'Apply the relevant CAF phases (Strategy, Plan, Ready, Adopt, Govern, Manage) from AWS/Azure/GCP frameworks as appropriate.', 'Lift-and-shift without modernisation assessment; ignoring cost optimisation; underestimating network and security requirements', 'On-premises-only requirements; challenges with no cloud component; pure application development without infrastructure scope', '["technology","cloud","architecture","migration"]', true),
('Data Mesh Principles', 'When addressing data architecture challenges involving domain-oriented data ownership, data as a product, or federated governance', 'Apply the four principles: domain ownership, data as a product, self-serve data platform, federated computational governance.', 'Implementing data mesh without organisational readiness; creating data silos instead of federated ownership; ignoring data quality accountability', 'Centralised data warehouse projects; small data teams; challenges without multiple data domains', '["technology","data","architecture"]', true),
('Zero Trust Security Model', 'When security architecture is central to the challenge, particularly for challenges involving sensitive data or multi-party access', 'Apply never-trust-always-verify principles: microsegmentation, least-privilege access, continuous verification, assume breach.', 'Treating Zero Trust as a product purchase rather than architecture principle; ignoring user experience impact; boiling the ocean rather than iterating', 'Isolated internal systems with no external access; challenges without security requirements; early prototypes where security is not yet a concern', '["technology","security","architecture"]', true),

-- FINANCIAL & INVESTMENT FRAMEWORKS (27-40)
('NPV / DCF Analysis', 'When evaluating the financial viability of a challenge solution, comparing investment alternatives, or justifying budget allocation', 'Calculate Net Present Value using projected cash flows (cost savings or revenue), appropriate discount rate (WACC), and realistic time horizon.', 'Overly optimistic cash flow projections; ignoring implementation costs; using inappropriate discount rates; not sensitivity-testing assumptions', 'Non-financial challenges; challenges where qualitative benefits outweigh quantitative; early ideation before costs are estimable', '["finance","investment","valuation"]', true),
('Total Cost of Ownership (TCO)', 'When comparing solution alternatives that have different cost structures across acquisition, implementation, operation, and decommissioning', 'Calculate full lifecycle costs including: acquisition, implementation, training, operations, maintenance, support, decommissioning. Compare alternatives on equal time horizons.', 'Excluding hidden costs (training, integration, opportunity cost); comparing different time horizons; ignoring cost of switching', 'Challenges focused on revenue generation rather than cost; qualitative comparison exercises; early-stage ideation', '["finance","procurement","cost_optimisation"]', true),
('Real Options Analysis', 'When the challenge involves staged investment decisions under uncertainty, or when flexibility and optionality have significant value', 'Identify embedded options (defer, expand, contract, abandon, switch). Value the option using appropriate models. Frame staged investments.', 'Over-complicating simple investment decisions; ignoring the cost of maintaining optionality; using options theory to justify indecision', 'Simple go/no-go decisions; challenges with low uncertainty; time-critical implementations where deferral is not an option', '["finance","investment","risk"]', true),
('Balanced Scorecard', 'When the challenge requires multi-dimensional performance measurement across financial, customer, process, and learning perspectives', 'Define objectives and KPIs for each of the four perspectives. Ensure cause-and-effect linkages between perspectives. Set targets and initiatives.', 'Creating too many KPIs; failing to establish cause-effect linkages; treating perspectives as independent silos', 'Pure financial analysis; single-dimensional performance tracking; challenges without ongoing performance management needs', '["finance","performance","strategy"]', true),
('Cost-Benefit Analysis (CBA)', 'When comparing the total expected costs against total expected benefits of a proposed solution to determine feasibility and ROI', 'Quantify all costs (direct, indirect, opportunity) and benefits (tangible, intangible) over the relevant time period. Calculate BCR and payback period.', 'Ignoring intangible costs/benefits; double-counting benefits; using inconsistent time horizons; not discounting future values', 'Mandatory compliance implementations (benefits are not optional); challenges where costs are fully pre-determined', '["finance","investment","planning"]', true),

-- RISK & GOVERNANCE FRAMEWORKS (33-45)
('ISO 31000 Risk Management', 'When the challenge requires structured risk identification, assessment, and treatment across technical, operational, or strategic dimensions', 'Apply the risk management process: establish context, identify risks, analyse (likelihood × impact), evaluate, treat (avoid/mitigate/transfer/accept).', 'Creating risk registers without actionable treatments; qualitative-only assessment when quantitative data exists; not updating risk assessments as context changes', 'Low-risk challenges with well-understood outcomes; pure creative/innovation exercises; challenges where all risks are pre-mitigated by design', '["risk","governance","compliance"]', true),
('FAIR (Factor Analysis of Information Risk)', 'When quantifying information security or technology risk in financial terms, particularly for cyber risk assessment', 'Decompose risk into Threat Event Frequency and Loss Magnitude. Use Monte Carlo simulation for probability distributions. Express risk in monetary terms.', 'Over-precise estimates with insufficient data; ignoring threat capability assessment; applying FAIR to qualitative risk scenarios', 'Non-technology risks; challenges without information assets at stake; qualitative risk discussions', '["risk","security","finance"]', true),
('NIST Cybersecurity Framework', 'When the challenge involves cybersecurity posture assessment, improvement, or compliance in technology solutions', 'Map relevant controls across the five functions: Identify, Protect, Detect, Respond, Recover. Assess current vs. target profile.', 'Treating as a compliance checklist rather than risk-based framework; implementing all controls without prioritisation; ignoring organisational context', 'Non-technology challenges; challenges without security requirements; pure business strategy', '["risk","security","compliance","technology"]', true),
('Monte Carlo Simulation', 'When quantifying uncertainty in project estimates, financial projections, or risk assessments with multiple variable inputs', 'Define input distributions for key variables, run 10,000+ iterations, analyse output distribution for confidence intervals and sensitivity.', 'Using point estimates disguised as distributions; insufficient iterations; ignoring correlations between input variables', 'Deterministic calculations; challenges with single-variable uncertainty; when simpler sensitivity analysis suffices', '["risk","finance","quantitative_analysis"]', true),
('Failure Mode and Effects Analysis (FMEA)', 'When systematically identifying potential failure modes in a process or system and prioritising them for mitigation', 'For each component/step: identify failure modes, determine effects, assess Severity × Occurrence × Detection to calculate Risk Priority Number (RPN).', 'Subjective scoring without calibration; not updating after changes; focusing only on high-RPN items while ignoring systemic patterns', 'Exploratory innovation challenges; early ideation; challenges without defined processes or systems to analyse', '["risk","quality","operations","engineering"]', true),

-- CHANGE MANAGEMENT & HR FRAMEWORKS (38-50)
('Kotter''s 8-Step Change Model', 'When the challenge involves organisational transformation, adoption of new processes, or cultural change', 'Apply sequentially: urgency, coalition, vision, communication, empowerment, quick wins, consolidation, anchoring. Map challenge phases to steps.', 'Skipping early steps (urgency/coalition); declaring victory too early; underestimating resistance', 'Pure technology implementations without change impact; challenges where change is already accepted; incremental improvements', '["change_management","transformation","leadership"]', true),
('ADKAR Model', 'When managing individual-level change adoption or diagnosing where change resistance occurs', 'Assess and address each element: Awareness, Desire, Knowledge, Ability, Reinforcement. Identify the barrier point for target users.', 'Treating ADKAR as linear when it is diagnostic; focusing only on training (Knowledge) while ignoring Desire; skipping Reinforcement', 'Challenges without human adoption requirements; pure technology or data challenges; challenges where users have no choice', '["change_management","adoption","training"]', true),
('Prosci Change Management Methodology', 'When structuring a comprehensive change management programme alongside a technical or operational solution', 'Apply the three-phase process: Prepare (readiness, sponsorship), Manage (plans for communication, training, resistance), Sustain (adoption, reinforcement).', 'Creating plans without executive sponsorship; treating change management as a communication exercise only; starting too late in the project', 'Technical challenges without organisational impact; challenges where all stakeholders are already aligned; one-person solutions', '["change_management","project_management","adoption"]', true),
('Stakeholder Analysis & Mapping', 'When identifying, categorising, and developing engagement strategies for challenge stakeholders', 'Map stakeholders on power/interest grid. Classify engagement approach: manage closely (high power/high interest), keep satisfied, keep informed, monitor.', 'Treating all stakeholders equally; ignoring informal influencers; static mapping without updating as dynamics change', 'Single-stakeholder challenges; internal self-improvement; challenges where stakeholders are pre-defined and aligned', '["change_management","governance","communication"]', true),
('Competency Framework Design', 'When the challenge involves defining skills, capabilities, or proficiency requirements for roles or teams', 'Define competency domains, proficiency levels, behavioural indicators, and assessment methods. Map to challenge requirements.', 'Creating overly complex frameworks; failing to differentiate proficiency levels meaningfully; ignoring context-specific competencies', 'Challenges without skills or team capability dimensions; pure technology or process challenges', '["hr","capability","assessment"]', true),

-- INNOVATION & DESIGN FRAMEWORKS (43-55)
('Design Thinking (Stanford d.school)', 'When the challenge requires human-centred problem solving, user empathy, or innovative solution design', 'Apply iteratively: Empathise (user research), Define (problem framing), Ideate (solution brainstorming), Prototype (rapid testing), Test (validation).', 'Skipping Empathise and jumping to solutions; treating Design Thinking as a linear waterfall; prototyping without real user testing', 'Well-defined technical problems with known solutions; compliance implementations; challenges where user needs are already validated', '["innovation","design","user_experience"]', true),
('Jobs to be Done (JTBD)', 'When understanding user motivations, unmet needs, or when the challenge involves product/service design', 'Identify the functional, emotional, and social jobs users are trying to accomplish. Frame the solution in terms of job outcomes, not features.', 'Confusing jobs with tasks; ignoring emotional and social dimensions; defining jobs too narrowly (solution-specific rather than outcome-oriented)', 'Infrastructure challenges without end-user impact; back-office process optimisation; challenges where the ''job'' is already defined in the brief', '["innovation","product","user_experience"]', true),
('Lean Startup Methodology', 'When the challenge involves hypothesis-driven development, MVP design, or iterative solution validation', 'Apply Build-Measure-Learn loops. Define the riskiest assumption, design the minimum experiment to test it, measure with actionable metrics.', 'Building too much before validating; vanity metrics over actionable metrics; pivoting without sufficient data; applying to challenges requiring full solutions', 'Challenges requiring complete, production-ready deliverables; regulated environments requiring full compliance upfront; challenges with fixed scope', '["innovation","product","agile"]', true),
('Technology Readiness Levels (TRL)', 'When assessing the maturity of a proposed technology solution or when the challenge spans multiple maturity stages', 'Map the solution to TRL 1-9 scale. Identify current TRL, target TRL, and the activities/evidence required to advance between levels.', 'Inflating TRL without supporting evidence; confusing prototype (TRL 4-5) with production-ready (TRL 8-9); not aligning TRL to challenge maturity expectations', 'Non-technology challenges; challenges where maturity is pre-defined; pure strategy or process challenges', '["innovation","technology","assessment"]', true),
('Stage-Gate Process (Cooper)', 'When managing innovation projects through structured decision gates with go/kill criteria', 'Define stages (scoping, business case, development, testing, launch) and gates (criteria for progressing). Map challenge phases to gates.', 'Making gates a formality rather than genuine decision points; too many gates for simple projects; not killing projects that fail gate criteria', 'Agile/iterative challenges; challenges requiring continuous delivery; single-phase implementations', '["innovation","project_management","governance"]', true),
('Wardley Mapping', 'When analysing technology or capability evolution, strategic positioning, or build-vs-buy decisions', 'Map components on the value chain (y-axis) against evolution stage (Genesis → Custom → Product → Commodity on x-axis). Identify strategic plays.', 'Creating maps without validating component positioning; ignoring climate patterns; static maps without scenario exploration', 'Operational challenges without strategic technology decisions; pure process improvement; challenges with pre-selected technology stack', '["strategy","technology","architecture"]', true),
('Double Diamond (Design Council)', 'When structuring a discovery-to-delivery process, particularly for challenges requiring both problem exploration and solution design', 'Apply four phases: Discover (diverge on problem), Define (converge on problem), Develop (diverge on solutions), Deliver (converge on solution).', 'Rushing through the first diamond (problem space); not truly diverging before converging; treating as waterfall rather than iterative', 'Challenges with pre-defined problems and solution requirements; pure implementation; compliance-driven projects', '["innovation","design","process_improvement"]', true),

-- DATA & ANALYTICS FRAMEWORKS (50-60)
('CRISP-DM (Cross-Industry Standard Process for Data Mining)', 'When the challenge involves data analytics, machine learning, or data-driven decision making', 'Apply the six phases: Business Understanding, Data Understanding, Data Preparation, Modelling, Evaluation, Deployment. Iterate as needed.', 'Jumping to modelling without business understanding; insufficient data preparation (garbage in, garbage out); evaluating with wrong metrics', 'Challenges without data components; pure process or organisational challenges; challenges where data is not available or accessible', '["data","analytics","machine_learning"]', true),
('Data Quality Dimensions (DAMA)', 'When assessing or improving data quality as part of a challenge involving data integration, migration, or analytics', 'Evaluate against key dimensions: Accuracy, Completeness, Consistency, Timeliness, Validity, Uniqueness. Quantify current state and set targets.', 'Focusing on all dimensions equally rather than prioritising by business impact; measuring without establishing baselines; quality checks as one-off rather than continuous', 'Challenges without data quality concerns; greenfield systems without existing data; pure infrastructure challenges', '["data","quality","governance"]', true),
('DAMA-DMBOK Data Management Framework', 'When the challenge requires comprehensive data management strategy including governance, architecture, quality, and security', 'Apply relevant knowledge areas: Data Governance, Data Architecture, Data Modelling, Data Quality, Data Security, Master Data Management.', 'Implementing all knowledge areas simultaneously; treating data management as a technology problem rather than organisational capability; ignoring data culture', 'Small single-dataset challenges; challenges without ongoing data management needs; one-time data extraction tasks', '["data","governance","architecture"]', true),

-- PROCUREMENT & SOURCING FRAMEWORKS (53-60)
('Kraljic Portfolio Purchasing Model', 'When the challenge involves procurement strategy, supplier management, or sourcing decisions', 'Classify items on profit impact (high/low) vs. supply risk (high/low): Strategic, Bottleneck, Leverage, Non-Critical. Apply appropriate strategies.', 'Classifying items without data; applying the same strategy to all quadrants; ignoring supplier relationship dynamics', 'Non-procurement challenges; challenges where suppliers are pre-selected; internal capability development', '["procurement","strategy","supply_chain"]', true),
('Make vs. Buy Analysis', 'When deciding whether to build a solution internally, buy commercial off-the-shelf, or outsource development', 'Evaluate across dimensions: cost (TCO), time-to-value, strategic importance, available capability, risk, and IP considerations.', 'Focusing only on cost; ignoring long-term maintenance burden; underestimating internal capability gaps; not considering hybrid options', 'Challenges where the make/buy decision is already made; pure implementation challenges; challenges with mandated technology', '["procurement","strategy","technology"]', true),

-- PROJECT MANAGEMENT FRAMEWORKS (55-65)
('Critical Path Method (CPM)', 'When the challenge involves project scheduling, identifying dependencies, or optimising timeline for complex multi-phase work', 'Map all activities with durations and dependencies. Calculate forward and backward pass to identify the critical path and float for non-critical activities.', 'Ignoring resource constraints; not updating the critical path as the project progresses; confusing critical path with longest path in resource-constrained schedules', 'Simple challenges with few dependencies; agile/iterative delivery; challenges without timeline constraints', '["project_management","planning","scheduling"]', true),
('PRINCE2 Framework', 'When structured project governance with defined roles, stages, and controls is required, particularly in government or regulated contexts', 'Apply the seven principles (business justification, learn from experience, defined roles, manage by stages, manage by exception, focus on products, tailor).', 'Applying full PRINCE2 to small projects; excessive documentation; treating stages as waterfall phases rather than control points', 'Agile-first organisations; small, informal projects; innovation challenges requiring flexibility over structure', '["project_management","governance","methodology"]', true),
('Earned Value Management (EVM)', 'When tracking project performance against budget and schedule baselines with quantitative metrics', 'Calculate PV, EV, AC. Derive CPI (EV/AC) and SPI (EV/PV). Project EAC and ETC. Flag variances exceeding thresholds.', 'Applying to agile work without adaptation; not rebasing after approved scope changes; using EVM for cost tracking without schedule integration', 'Early-stage projects without baselines; exploratory R&D; challenges without budget tracking requirements', '["project_management","finance","performance"]', true),
('Work Breakdown Structure (WBS)', 'When decomposing a complex challenge into manageable work packages for estimation, assignment, and tracking', 'Decompose top-down using the 100% rule (each level captures all work). Deliverable-oriented decomposition. 3-5 levels typical.', 'Activity-oriented instead of deliverable-oriented; inconsistent decomposition levels; missing work packages (violating 100% rule)', 'Agile backlogs (use story mapping instead); simple single-deliverable challenges; challenges where the WBS is pre-defined', '["project_management","planning","scoping"]', true),

-- SUSTAINABILITY & ESG FRAMEWORKS (59-65)
('ESG Materiality Assessment', 'When the challenge involves sustainability strategy, ESG reporting, or identifying material environmental/social/governance issues', 'Identify ESG topics, assess materiality (impact on business + impact on stakeholders), prioritise, map to reporting frameworks (GRI, SASB, TCFD).', 'Boiling the ocean on ESG topics; stakeholder washing (selecting convenient stakeholders); treating materiality as static', 'Challenges without sustainability dimensions; pure technology implementations; challenges where ESG is not relevant to stakeholders', '["sustainability","governance","strategy"]', true),
('Circular Economy Framework', 'When the challenge involves resource efficiency, waste reduction, product lifecycle design, or sustainable business models', 'Apply the ReSOLVE framework: Regenerate, Share, Optimise, Loop, Virtualise, Exchange. Identify circular opportunities in the value chain.', 'Focusing only on recycling (downstream) while ignoring design for circularity (upstream); greenwashing linear processes as circular', 'Challenges without physical product or resource dimensions; pure digital/software challenges; challenges where linear models are mandated', '["sustainability","operations","innovation"]', true),

-- CUSTOMER & MARKETING FRAMEWORKS (61-70)
('Customer Journey Mapping', 'When the challenge involves understanding and improving customer/user experience across touchpoints', 'Map stages (awareness, consideration, purchase, retention, advocacy), touchpoints, emotions, pain points, and opportunities across the journey.', 'Mapping the ideal journey rather than actual experience; ignoring emotional dimensions; creating maps without customer research data', 'Internal process challenges without customer impact; B2B infrastructure; challenges where the customer journey is not relevant', '["customer","design","user_experience"]', true),
('Net Promoter Score (NPS) Framework', 'When measuring customer satisfaction, loyalty, or when the challenge targets improved customer advocacy', 'Measure NPS (% Promoters - % Detractors), segment by cohort, identify root cause drivers through follow-up analysis, set improvement targets.', 'Using NPS as the sole satisfaction metric; not following up with root cause analysis; comparing NPS across industries without context', 'Internal operational challenges; challenges without end-customer measurement; early-stage products without a customer base', '["customer","performance","measurement"]', true),
('Service Blueprint', 'When designing or improving service delivery with both front-stage (customer-facing) and back-stage (operational) components', 'Map customer actions, front-stage interactions, back-stage processes, and support systems. Identify fail points and wait points.', 'Focusing only on front-stage without operational design; creating blueprints without customer input; not linking to technology architecture', 'Pure technology challenges; challenges without service delivery components; product manufacturing', '["customer","operations","design"]', true),

-- COMMUNICATION & PRESENTATION FRAMEWORKS (64-70)
('Pyramid Principle (Minto)', 'When structuring challenge narratives, recommendations, or reports for executive audiences', 'Lead with the answer/recommendation. Support with 3-5 mutually exclusive, collectively exhaustive (MECE) arguments. Provide evidence for each.', 'Burying the recommendation at the end; non-MECE groupings; too many levels of detail for the audience; telling the story chronologically rather than logically', 'Technical documentation requiring sequential instruction; data appendices; challenges where the audience expects exploratory narrative', '["communication","strategy","consulting"]', true),
('MECE Principle (Mutually Exclusive, Collectively Exhaustive)', 'When structuring problem decomposition, categorisation, or analysis to ensure completeness without overlap', 'Decompose the problem into categories that do not overlap (ME) and together cover the entire problem space (CE). Test both conditions explicitly.', 'Creating categories that overlap; missing categories that leave gaps; applying MECE to naturally continuous variables', 'Creative brainstorming (where overlap is productive); challenges requiring lateral thinking; simple binary decisions', '["consulting","analysis","problem_solving"]', true),
('Issue Tree / Logic Tree', 'When decomposing a complex problem into component parts for systematic analysis and hypothesis testing', 'Start with the key question, decompose into sub-issues (MECE), further decompose until actionable hypotheses emerge. Prioritise branches by impact.', 'Non-MECE decomposition; going too deep on low-impact branches; treating issue trees as static rather than iteratively refined', 'Well-understood problems with known solutions; challenges requiring creative/lateral approaches; simple single-issue problems', '["consulting","analysis","problem_solving"]', true),
('Hypothesis-Driven Problem Solving', 'When the challenge benefits from testing assumptions early, or when rapid structured analysis is needed', 'Formulate initial hypothesis (day-one answer), identify what must be true for the hypothesis to hold, design analyses to test, iterate.', 'Confirmation bias (seeking only supporting evidence); not revising hypotheses when evidence contradicts; over-investing in analysis before testing', 'Open-ended exploration; challenges where hypotheses cannot be formed due to insufficient context; creative design challenges', '["consulting","analysis","problem_solving"]', true),

-- GOVERNANCE & COMPLIANCE FRAMEWORKS (68-80)
('COSO Internal Control Framework', 'When designing or assessing internal controls, particularly for financial reporting, operations, or compliance objectives', 'Evaluate across five components: Control Environment, Risk Assessment, Control Activities, Information & Communication, Monitoring Activities.', 'Treating controls as checkbox compliance; not linking controls to specific risks; designing controls without considering cost-effectiveness', 'Challenges without internal control requirements; pure innovation; early-stage startup environments', '["governance","compliance","risk","finance"]', true),
('GDPR Compliance Framework', 'When the challenge involves personal data processing, privacy by design, or data subject rights within EU/EEA jurisdictions', 'Apply six lawful bases assessment, data mapping, DPIA for high-risk processing, privacy by design principles, data subject rights mechanisms.', 'Relying solely on consent when legitimate interest applies; not documenting lawful basis; treating GDPR as a one-time project rather than ongoing compliance', 'Challenges not involving personal data; non-EU/EEA jurisdictions without adequacy requirements; anonymised data only', '["compliance","privacy","data","regulatory"]', true),
('SOC 2 Type II Controls', 'When the challenge involves demonstrating security, availability, processing integrity, confidentiality, or privacy controls to enterprise customers', 'Map controls to Trust Services Criteria. Design evidence collection. Establish continuous monitoring for the audit period.', 'Designing controls for audit rather than security; manual evidence collection instead of automated; treating SOC 2 as a security programme rather than attestation', 'Non-enterprise-facing solutions; challenges without compliance attestation requirements; early prototypes', '["compliance","security","governance"]', true),

-- ADDITIONAL CONSULTING FRAMEWORKS (71-80)
('Capability Maturity Model Integration (CMMI)', 'When assessing organisational process maturity or when the challenge involves process improvement across maturity levels', 'Assess current maturity level (1-5: Initial, Managed, Defined, Quantitatively Managed, Optimising). Define target level and improvement roadmap.', 'Pursuing higher maturity levels without business justification; treating levels as goals rather than means; ignoring that Level 1→2 delivers the most impact per effort', 'Challenges not involving process capability; one-time implementations; challenges where process maturity is irrelevant', '["operations","quality","process_improvement","governance"]', true),
('Business Model Canvas', 'When analysing or designing business models, particularly for challenges involving new ventures, revenue models, or value propositions', 'Complete all nine blocks: Value Propositions, Customer Segments, Channels, Customer Relationships, Revenue Streams, Key Resources, Key Activities, Key Partnerships, Cost Structure.', 'Filling blocks independently without testing coherence; treating the canvas as static; confusing the canvas with a business plan', 'Pure technical implementation challenges; operational efficiency within an existing model; challenges where the business model is fixed', '["strategy","innovation","business_design"]', true),
('McKinsey Three Horizons', 'When the challenge involves balancing short-term performance with medium and long-term growth or innovation', 'Map initiatives to H1 (core business, immediate), H2 (emerging opportunities, 2-3 years), H3 (transformational, 3-5+ years). Allocate resources proportionally.', 'Ignoring H2/H3 under short-term pressure; placing immature ideas in H1; not adjusting horizon placement as initiatives mature', 'Single-horizon challenges; immediate operational fixes; challenges without a time-horizon dimension', '["strategy","innovation","portfolio"]', true),
('Cynefin Framework', 'When determining the appropriate management approach based on problem complexity (simple, complicated, complex, chaotic)', 'Classify the challenge context. Clear → apply best practice. Complicated → analyse and apply good practice. Complex → probe-sense-respond. Chaotic → act-sense-respond.', 'Treating complex problems as complicated (analysis paralysis); not recognising context shifts during execution; applying ordered-domain practices to complex challenges', 'Challenges where context is obvious; simple process documentation; challenges with clear right answers', '["strategy","complexity","decision_making"]', true),
('Root Cause Analysis (5 Whys + Fishbone)', 'When the challenge requires understanding underlying causes of problems rather than symptoms', 'Ask ''why'' iteratively (5+ times) to drill past symptoms. Use Ishikawa (fishbone) to categorise causes: Methods, Machines, Materials, Manpower, Measurement, Environment.', 'Stopping at superficial answers; single causal chain thinking (most problems are multi-causal); blame-oriented rather than system-oriented analysis', 'Forward-looking strategy challenges; innovation/design challenges; challenges where root cause is already known and validated', '["operations","quality","problem_solving"]', true),
('Pareto Analysis (80/20 Rule)', 'When prioritising efforts, identifying the vital few causes of problems, or optimising resource allocation', 'Collect data, rank items by frequency/impact, calculate cumulative percentage, identify the 20% of causes driving 80% of impact. Focus effort there.', 'Assuming the exact 80/20 split applies universally; ignoring the long tail when it matters; not validating the distribution with actual data', 'Challenges requiring comprehensive coverage; compliance where all items must be addressed; challenges with uniform distribution of causes', '["operations","analysis","prioritisation"]', true),
('Gap Analysis Framework', 'When assessing the difference between current state and desired future state to define the challenge scope and required interventions', 'Define current state (with evidence), define target state (with measurable criteria), identify gaps, prioritise gaps, define interventions for each.', 'Aspirational target states without achievability assessment; gaps without root cause analysis; interventions without measurable outcomes', 'Greenfield challenges (no current state to compare); challenges where current state is well-understood; pure innovation without a baseline', '["consulting","planning","assessment"]', true),
('Benchmarking Framework', 'When comparing performance against industry standards, best practices, or competitor capabilities to calibrate challenge targets', 'Select benchmark dimensions, identify comparison set (industry peers, best-in-class, internal units), collect data, normalise for comparability, identify gaps.', 'Comparing unlike organisations without normalisation; benchmarking outputs without understanding inputs; setting targets at benchmark without considering context', 'Challenges without comparable benchmarks; truly novel solutions; challenges where internal improvement is more relevant than external comparison', '["consulting","performance","measurement"]', true);
