-- Principal-grade exemplar rewrites for 26 remaining curation sections.
-- Anchored to the GlobalTech / SAP EWM logistics challenge narrative.

-- ── 6 previously NULL sections ─────────────────────────────────────────────

UPDATE public.ai_review_section_config SET example_good =
'GlobalTech Logistics Legal Office mandates: (1) all proposed solutions must comply with EU GDPR Art. 28 (data processor obligations) and California CPRA §1798.140 for cross-border warehouse telemetry; (2) any IP arising from the engagement is governed by the executed CPA Schedule 4 (Joint IP, with Seeker holding exclusive commercial rights in logistics vertical, Solver retaining background IP); (3) no open-source components under copyleft licenses (GPL v2/v3, AGPL) may be embedded in the production bundle — MIT, Apache 2.0, BSD-3 are pre-approved; (4) sub-processor disclosure required at submission per Schedule 6; (5) export-control review (EAR 99 / dual-use) applies to any ML model weights shipped outside the EEA. Solvers must counter-sign the NDA (Schedule 1) before accessing the data room. Contact: legal-ops@globaltech-logistics.example for clarifications. Consistent with IP Model = Joint and Legal Docs tier = Standard+.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'creator_legal_instructions';

UPDATE public.ai_review_section_config SET example_good =
'Curated reference set provided by GlobalTech Operations: (1) Internal — "EWM Pick-Path Latency Audit, Q3 2024" (PDF, 42 pp.) shared via the data room; (2) Internal — "Warehouse 7 Layout & Slotting Map v3.1" (DWG + PDF); (3) External — Gartner, "Magic Quadrant for Warehouse Management Systems, 2024" (G00795112); (4) External — SAP Note 2982024 "EWM RF Performance Tuning"; (5) Academic — Boysen et al., "Warehousing in the e-commerce era," Eur. J. Oper. Res. 277(2), 2019, pp. 396–411; (6) Standards — ISO 22400-2:2014 (KPI definitions for manufacturing/warehouse operations) and VDI 4490 (logistics performance metrics). Solvers should treat (1)–(2) as authoritative facts about the current state and (3)–(6) as benchmark calibration. All references are aligned with Context & Background and Current Deficiencies sections.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'creator_references';

UPDATE public.ai_review_section_config SET example_good =
'Evaluation configuration: PANEL method with 3 expert reviewers per submission, weighted-average scoring on a 0–100 scale. Reviewer pool: 1× SAP EWM SME (weight 0.40), 1× Warehouse Operations Lead (weight 0.35), 1× Data/ML Engineer (weight 0.25). Scoring rubric mirrors Evaluation Criteria (Technical Feasibility 30, Operational Impact 30, Implementation Risk 20, Cost-to-Value 20). Quorum: minimum 2 of 3 reviewers must score; missing scores re-routed within 48h SLA. Calibration: pilot scoring on 2 dummy submissions before live review (inter-rater reliability target Krippendorff α ≥ 0.70). Conflict-of-interest disqualification per platform policy. Aggregation: drop highest and lowest only if spread > 25 points; otherwise weighted mean. Tie-break: SAP EWM SME score is decisive. Results published to Solver within 10 business days of panel close.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'evaluation_config';

UPDATE public.ai_review_section_config SET example_good =
'GlobalTech Logistics is a Tier-1 European 3PL operator (HQ Rotterdam, NL) with 18 distribution centres across DACH, Benelux, and the Nordics, ~4,200 FTEs, and EUR 1.1B FY2024 revenue. The Seeker unit is the Operations Excellence Office reporting to the COO, with a mandate to drive a 15% productivity uplift across the network by FY2026 (Board-approved OKR). The organisation runs SAP S/4HANA 2022 with Decentralised EWM 2022 across 12 of 18 sites; the remaining 6 sites are on legacy WMS scheduled for migration in 2026. Existing data & analytics maturity: Level 3 of 5 on the Gartner ITScore for D&A — strong descriptive reporting, limited predictive deployment. Engagement sponsor: VP Operations Excellence (decision authority up to EUR 750k); steering committee meets bi-weekly. Procurement vehicle: existing Master Services Framework eligible, fast-tracking onboarding to ~10 business days post-award.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'organization_context';

UPDATE public.ai_review_section_config SET example_good =
'Authoritative external URLs supporting the brief: (1) https://help.sap.com/docs/SAP_EXTENDED_WAREHOUSE_MANAGEMENT — official SAP EWM 2022 documentation (RF framework, queue management, wave planning); (2) https://www.iso.org/standard/56847.html — ISO 22400-2:2014 KPI standard cited in Success Metrics; (3) https://www.gartner.com/en/documents/4012345 — Gartner WMS Magic Quadrant 2024 (subscription-gated; summary in data room); (4) https://www.warehousingeducation.org/research/pick-path-benchmarks — WERC 2024 DC Measures benchmark report (industry pick rates by DC archetype); (5) https://eur-lex.europa.eu/eli/reg/2016/679/oj — GDPR full text (referenced in Creator Legal Instructions). All links verified live as of brief publication; mirrored copies available in the data room for audit.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'reference_urls';

UPDATE public.ai_review_section_config SET example_good =
'Target solver audience: Certified SAP EWM implementation partners (Gold/Platinum SAP PartnerEdge tier) AND independent boutique consultancies (5–50 FTEs) with demonstrable warehouse optimisation track record (≥3 reference engagements in the last 24 months at EU 3PL or retail DCs of ≥10k SKU complexity). Optional but valued: hands-on operations research experience (CPLEX, Gurobi, OR-Tools) and ML/RL pick-path optimisation case studies. Geographic eligibility: EU/EEA-based or with established EU subsidiary (GDPR data-processor compliance). Excluded: pure software resellers without implementation muscle, and providers with active engagements at three named direct competitors (list in data room, NDA-gated). Audience size estimate: ~140 qualifying providers in the platform pool; expected applicant funnel ~25–35 based on prior similar challenges. Aligned with Eligibility and Solver Expertise sections.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'solver_audience';

-- ── 21 junior-grade sections — Principal rewrites ─────────────────────────

UPDATE public.ai_review_section_config SET example_good =
'Primary stakeholders (RACI-mapped): COO (Accountable) — owns the 15% productivity OKR; VP Operations Excellence (Responsible sponsor) — programme owner, EUR 750k decision authority; Site Directors of the 4 pilot DCs in Rotterdam, Hamburg, Antwerp, Düsseldorf (Responsible operationally) — daily floor adoption and shift-level rollout; Head of SAP CoE (Consulted) — gates EWM configuration changes via internal Change Advisory Board; Works Council representatives (Consulted) — co-determination rights under DE/NL labour law for any change affecting picker workload or measurement; Frontline pickers (~850 across pilot sites, Informed) — usability and trust in new pick-path guidance; IT Security & DPO (Consulted) — sign-off on telemetry data flows; external SAP partner of record (Informed) — coordination on EWM patch windows. Misalignment risk: Works Council non-engagement has historically delayed two prior initiatives by 4–6 months; mitigation requires formal consultation by Phase 3.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'affected_stakeholders';

UPDATE public.ai_review_section_config SET example_good =
'Out of scope and explicitly de-prioritised: (1) Greenfield WMS replacement or migration off SAP EWM — investment thesis assumes EWM remains the system of record through 2028; (2) Hardware replacement of RF guns or voice-pick headsets — current Zebra TC52 fleet (~3,200 devices) was refreshed in 2023 and is under depreciation lock; (3) Workforce reduction proposals — productivity gains must be reinvested in throughput growth, not headcount cuts (Works Council commitment); (4) Fully autonomous mobile robotics (AMR/AGV) deployment — separate parallel initiative under different sponsor, do not duplicate; (5) Black-box ML models without explainability — any predictive component must expose feature attribution to operations supervisors (SHAP or equivalent); (6) Cloud-only architectures requiring egress of pick-event telemetry outside EU/EEA — disqualifying per GDPR posture. Solvers proposing any of the above will be marked non-conforming at evaluation.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'approaches_not_of_interest';

UPDATE public.ai_review_section_config SET example_good =
'Complexity rated HIGH (Tier 4 of 5 on platform complexity rubric). Drivers: (1) Multi-site rollout across 4 pilot DCs with heterogeneous layouts and SKU profiles (variance coefficient 0.42 on pick density); (2) Tight SAP EWM 2022 integration constraints — custom BAdI development requires SAP CoE governance and 6-week change windows; (3) Dual-stack data plane (on-prem EWM + cloud analytics) requiring secure tunnel architecture; (4) Regulatory load — GDPR, Works Council co-determination, EU AI Act risk classification (limited risk tier expected for productivity-assist use case); (5) Stakeholder count ≥7 with veto-capable parties (Works Council, SAP CoE, DPO); (6) Outcome measurability requires controlled A/B with matched-site control to isolate effect from seasonality. Estimated effort: 14–18 FTE-weeks for design+pilot, 8–12 FTE-weeks for production hardening. Aligned with Solver Expertise (senior+ profile required).',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'complexity';

UPDATE public.ai_review_section_config SET example_good =
'GlobalTech operates 18 European DCs running SAP EWM 2022 (Decentralised) on S/4HANA 2022, processing ~2.4M outbound order lines per month with average pick rates of 78 lines/picker-hour — 22% below the WERC 2024 benchmark of 100 lines/picker-hour for comparable mid-piece DCs. The Operations Excellence Office launched the "Network Productivity 2026" programme in Q1 2024 with a Board-mandated OKR of +15% productivity by end of FY2026. Three prior interventions (slotting refresh 2023, voice-pick rollout 2022, shift-level dashboarding 2024) collectively delivered ~6% gain — leaving a ~9% residual gap. Diagnostic work in Q3 2024 (referenced in the data room) localised the largest remaining lever to pick-path inefficiency and wave-release timing, particularly during the 14:00–18:00 peak when wave overlap creates aisle congestion. This challenge targets that lever and is sequenced after the 2025 EWM patch consolidation completes (March 2025).',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'context_and_background';

UPDATE public.ai_review_section_config SET example_good =
'Current state deficiencies (quantified, sourced from Q3 2024 diagnostic, data room ref D-04): (1) Average pick travel distance 218m per order vs. theoretical optimum of 142m — 35% travel overhead, equating to ~2.1 FTE-shifts of unproductive walking per DC per day; (2) Wave-release algorithm uses fixed time slots (every 90 min) ignoring real-time aisle congestion — peak aisles 7-12 hit 140% of design throughput between 15:00–17:00, causing pick-confirmation latency spikes (p95 jumps from 2.3s to 11.7s); (3) Slotting refresh runs quarterly via static ABC analysis — fast-mover drift between refreshes adds an estimated 4–6% to travel; (4) No closed-loop feedback from pick events back into wave planning — supervisor overrides are anecdotal, not data-driven; (5) Picker-level performance variance is 2.3× (top quartile vs. bottom quartile) with no targeted coaching signal. Cumulative deficiency value: ~EUR 14.5M/year across the 18-site network at FY2024 labour rates.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'current_deficiencies';

UPDATE public.ai_review_section_config SET example_good =
'Data resources provided in the secure data room (NDA-gated, 90-day access post-award): (1) 12 months of EWM pick-confirmation transactions across 4 pilot DCs (~58M rows, columnar Parquet, ~12 GB) with picker_id pseudonymised per GDPR; (2) Warehouse master data — slotting maps, aisle topology (DWG+JSON), SKU dimensions and velocity bands; (3) Wave-planning configuration exports (EWM /SCWM/WAVE tables, anonymised); (4) Hourly aisle-traffic heatmaps from RTLS pilot (Q4 2024, Rotterdam only); (5) Labour calendar and shift patterns; (6) Pre-computed baseline KPIs aligned with ISO 22400-2 (lines/hr, travel/order, on-time-pick rate). Refresh cadence: monthly snapshot during the engagement. Not provided (must be inferred or requested via Q&A): real-time order stream (offered as a 2-week sandbox feed in Phase 4 only), competitor benchmark data, and individual picker performance reviews (excluded for Works Council reasons).',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'data_resources_provided';

UPDATE public.ai_review_section_config SET example_good =
'Domain tags (controlled vocabulary, max 8): supply-chain, warehouse-management, sap-ewm, operations-research, predictive-analytics, process-optimisation, logistics-3pl, eu-gdpr-compliance. Primary domain: Supply Chain & Logistics (NACE H 52.10). Secondary: Enterprise Software (SAP ecosystem). Tertiary: Applied OR/ML. Tags chosen for matching against platform Solver pool taxonomy and for industry framework retrieval (TOGAF for integration architecture, DMAIC for the diagnostic-improve-control cycle, SCOR 13.0 for warehouse process reference). Tags are consistent with Industry Segment and Functional Area fields and with the framework library entries seeded under the same domains. Avoid generic tags (e.g., "AI", "digital-transformation") which dilute matching precision.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'domain_tags';

UPDATE public.ai_review_section_config SET example_good =
'Eligibility criteria: (1) Legal entity registered in EU/EEA or with established EU subsidiary capable of executing as a GDPR data processor under Art. 28; (2) Minimum 3 reference engagements in the last 24 months at EU 3PL or retail distribution centres of ≥10,000 active SKUs and ≥150 pickers per site; (3) SAP PartnerEdge Gold or Platinum tier OR demonstrable SAP EWM 2022 implementation experience (named project, named client, contactable reference); (4) Demonstrable operations research / optimisation capability — at least one published case study, white paper, or anonymised reference architecture using CPLEX, Gurobi, OR-Tools, or comparable; (5) Insurance: Professional Indemnity ≥ EUR 5M, Cyber Liability ≥ EUR 2M; (6) No active engagement with three named direct competitors (NDA-gated list); (7) Counter-signed NDA before data-room access. Disqualifiers: pure software resellers, sanctioned entities, prior breach of platform code of conduct.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'eligibility';

UPDATE public.ai_review_section_config SET example_good =
'Escrow funding: total prize pool of EUR 180,000 fully funded into platform escrow at challenge publication (Phase 4 gate). Funding source: Operations Excellence FY2025 OpEx budget, PO #4500-2025-0142, approved by VP Operations Excellence within delegated authority (no Board approval required, threshold EUR 750k). Escrow currency: EUR. Tier breakdown matches Reward Structure (Platinum EUR 100k, Gold EUR 50k, Silver EUR 30k). Release conditions: (1) winner determination by panel quorum per Evaluation Config; (2) IP transfer / licence execution per CPA Schedule 4; (3) no outstanding compliance flags. Anti-clawback: funds released within 10 business days of award decision, no reversibility absent fraud finding. Currency hedging: not required (EUR-denominated end-to-end). Escrow agent: platform default. Solver payment details captured at submission and verified pre-release.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'escrow_funding';

UPDATE public.ai_review_section_config SET example_good =
'Expected outcomes (measurable, time-bounded): (1) Pilot deployment at 4 DCs by end of Phase 7 demonstrating ≥10% lift in lines/picker-hour (vs. matched-site control, p<0.05, 4-week observation); (2) Travel-distance reduction ≥20% per order (ISO 22400-2 KPI 14); (3) Pick-confirmation p95 latency held below 4.0s during peak window (14:00–18:00); (4) Production-ready integration package compatible with SAP EWM 2022 standard BAdI extension points — zero modifications to SAP core code; (5) Operations runbook + supervisor playbook documenting overrides, rollback, and incident handling; (6) Knowledge transfer to internal SAP CoE (2 named engineers) sufficient for them to operate the solution post-handover. Stretch outcome: validated rollout plan covering remaining 14 DCs with effort and cost estimates accurate to ±15%. Outcomes are consistent with Deliverables D1–D5 and Success Metrics KPIs.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'expected_outcomes';

UPDATE public.ai_review_section_config SET example_good =
'Cut warehouse pick travel by 20% and lift picker productivity 10% across four EU distribution centres — without replacing SAP EWM, without cutting headcount, and within a 14-week pilot. EUR 180k prize pool, GDPR-compliant, decision in 16 weeks.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'hook';

UPDATE public.ai_review_section_config SET example_good =
'IP model: JOINT IP per CPA Schedule 4. Background IP retained by each party (Solver retains pre-existing libraries, optimisation engines, accelerators; Seeker retains EWM configuration, master data, operational know-how). Foreground IP — anything created specifically for this engagement (custom BAdI code, trained models, configuration packages, runbooks) — is jointly owned with Seeker holding an exclusive, perpetual, royalty-free commercial licence within the logistics & 3PL vertical (NACE H 49–53), and Solver retaining the right to commercialise outside that vertical. Source code escrow: required for any model artefacts, deposited with platform escrow agent within 30 days of go-live. Open-source: copyleft (GPL/AGPL) prohibited in foreground deliverables; permissive licences (MIT, Apache 2.0, BSD-3) pre-approved with SBOM disclosure. Patent prosecution: joint, costs split 50/50, Seeker as lead. Aligned with Creator Legal Instructions and Legal Docs tier.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'ip_model';

UPDATE public.ai_review_section_config SET example_good =
'Legal documents pack (Tier: Standard+, assembled per platform Legal Architecture V2): (1) Mutual NDA — Schedule 1, executed pre-data-room access, 3-year confidentiality term; (2) Challenge Participation Agreement (CPA) — Schedule 2, governs submission rights, evaluation, and award; (3) Master Services Framework call-off — Schedule 3, activates on award for the implementation phase; (4) IP Assignment & Licence — Schedule 4, encodes the Joint IP model described in IP Model section; (5) Data Processing Agreement — Schedule 5, GDPR Art. 28 compliant, names Solver as processor, lists permitted sub-processors; (6) Sub-processor Disclosure — Schedule 6, updated at submission; (7) Platform Workforce Agreement (PWA) — for any platform-assigned reviewers. All documents pre-frozen with SHA-256 integrity hash at Phase 3 gate per V2 protocol; any post-freeze amendment triggers re-acceptance. LC review completed; LC status = approved.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'legal_docs';

UPDATE public.ai_review_section_config SET example_good =
'Solution maturity expectation: PILOT-READY at submission, PRODUCTION-HARDENABLE within 8 weeks of award. Specifically, submitted artefacts must include: (1) a working prototype tested on the provided 12-month pick-event dataset demonstrating the proposed optimisation against a defined baseline, with reproducible Jupyter or equivalent notebooks; (2) an integration design document detailing SAP EWM 2022 extension points used (BAdI names, custom tables if any, queue/RFC interfaces), reviewed against SAP best-practice patterns; (3) a non-functional readiness assessment covering latency, throughput, failure modes, and rollback. Not required at submission: full production code-hardening, penetration test reports, or final SOC 2 mapping — these are deliverables of the post-award implementation phase. Maturity rubric: TRL 6 (technology demonstrated in relevant environment) at submission, TRL 8 (system complete and qualified) at end of pilot. Aligned with Solution Type and Deliverables.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'maturity_level';

UPDATE public.ai_review_section_config SET example_good =
'Phase schedule (CONTROLLED governance, all dates relative to challenge publication T0): Phase 4 Open-for-Submission — T0 to T0+28 days (4 weeks for solver discovery and proposal); Phase 5 Submission Window Close & Eligibility Screening — T0+29 to T0+35 (1 week, platform admin); Phase 6 Expert Panel Evaluation — T0+36 to T0+56 (3 weeks, 3-reviewer panel per Evaluation Config); Phase 7 Award & Contract Execution — T0+57 to T0+70 (2 weeks, CPA Schedule 3 call-off); Phase 8 Pilot Implementation — T0+71 to T0+168 (14 weeks, 4-DC rollout); Phase 9 Outcome Validation & KPI Sign-off — T0+169 to T0+196 (4 weeks, A/B analysis vs. matched-site control); Phase 10 Closeout & Knowledge Transfer — T0+197 to T0+217 (3 weeks). Total elapsed: ~31 weeks. Buffer: each phase carries a 10% calendar buffer; aggregate slack ~3 weeks. Critical path: panel evaluation → contract execution → pilot kickoff. Schedule respects EU summer slowdown (no critical milestones in weeks 30–33).',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'phase_schedule';

UPDATE public.ai_review_section_config SET example_good =
'Preferred technical approach (directional, not prescriptive — solvers may propose alternatives with justification): a hybrid optimisation architecture combining (1) deterministic operations-research routing for intra-wave pick-path sequencing (e.g., capacitated TSP variants solvable via Gurobi/OR-Tools within sub-second SLA per wave), and (2) a learning component for wave-release timing that adapts to observed aisle congestion (contextual bandit or lightweight RL with feature attribution via SHAP for supervisor explainability). Integration: invoked from SAP EWM via standard BAdI /SCWM/EX_WAVE_GEN_RULES and /SCWM/EX_TO_PICK_PATH, no SAP core modifications. Deployment: containerised microservice on Seeker''s EU-hosted Kubernetes cluster (AKS Frankfurt), latency budget 250ms p95 round-trip. Why this shape: it preserves EWM as system of record, isolates the algorithmic risk in a replaceable component, satisfies EU AI Act limited-risk classification with explainability, and matches the SAP CoE''s integration governance model. Open to alternatives that achieve the same constraints.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'preferred_approach';

UPDATE public.ai_review_section_config SET example_good =
'Root-cause analysis (5-Whys + Ishikawa, validated against Q3 2024 diagnostic data): Primary cause — wave-release algorithm in EWM is time-triggered (fixed 90-min slots) rather than congestion-aware, so during peak hours overlapping waves converge on the same aisles, producing queue-formation and idle-walk back-tracking. Contributing causes: (a) static slotting refresh cadence (quarterly) cannot keep pace with promotional SKU velocity shifts, adding 4–6% travel; (b) absence of closed-loop telemetry — supervisor overrides are anecdotal; (c) RF gun confirmation latency spikes during peak (p95 11.7s) cascade into picker idle time, masquerading as "slow pickers" when the bottleneck is actually downstream queue depth; (d) shift-handover at 14:00 coincides with order-cut peak, creating a structural collision. Underlying systemic cause: optimisation has historically been sub-process local (slotting team, voice-pick team, dashboards team) with no owner of the cross-process pick-flow as a system. This challenge targets the systemic cause via the wave+path coupling.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'root_causes';

UPDATE public.ai_review_section_config SET example_good =
'Solution type: SOFTWARE + SERVICES hybrid. Software component — a deployable optimisation service (containerised, EU-hosted) integrated to SAP EWM 2022 via standard BAdI extension points, providing (a) congestion-aware wave-release recommendations and (b) per-wave pick-path sequencing. Services component — design, integration, pilot deployment, change management, and knowledge transfer to Seeker''s SAP CoE over a 14-week implementation phase. Not a pure product purchase (no off-the-shelf SKU), not a pure consulting engagement (must leave a working software asset). Excluded categories: greenfield WMS replacement, hardware procurement, autonomous robotics integration. Solution category code (platform taxonomy): SW-OPT-LOG-04 (Logistics Optimisation Software, integration-led delivery). Aligned with Solution Maturity (PILOT-READY at submission, TRL 6→8 over pilot) and IP Model (Joint, vertical-exclusive licence).',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'solution_type';

UPDATE public.ai_review_section_config SET example_good =
'Solver expertise required (must-have unless marked optional): (1) SAP EWM 2022 hands-on configuration and BAdI development — minimum 2 named engineers each with ≥3 full-cycle EWM implementations; (2) Operations Research — at least 1 senior with formal OR background (MSc/PhD or equivalent industry experience) and proficiency in Gurobi, CPLEX, or OR-Tools, demonstrated via case study; (3) Applied ML — at least 1 ML engineer with production deployment experience (not just notebooks); contextual bandits or RL experience is a strong plus; (4) Data engineering — proficiency with columnar/Parquet at the 10s-of-GB scale, secure on-prem-to-cloud pipelines; (5) EU regulatory literacy — GDPR Art. 28 processor obligations, EU AI Act limited-risk classification awareness; (6) Optional but valued: Lean/Six Sigma Black Belt for the change-management track, German or Dutch language capability for site engagement. Team size expectation: 5–8 FTEs at peak. Aligned with Eligibility and Solver Audience.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'solver_expertise';

UPDATE public.ai_review_section_config SET example_good =
'Submission guidelines: Solvers must submit (1) a Technical Proposal (PDF, max 25 pages, 11pt min) covering approach, integration design, optimisation methodology, and risk register; (2) a Working Prototype Package — code repository (private GitHub or zip), reproducible Jupyter notebook(s) demonstrating proposed optimisation against the supplied 12-month dataset with measurable baseline comparison, and a 5-minute screen-recorded demo (MP4, ≤500MB); (3) a Commercial Schedule (Excel template provided in data room) with fixed-price pilot quote, T&M rate card for change requests, and assumptions; (4) a Team CV pack and three reference-engagement letters (named clients, contactable); (5) Sub-processor Disclosure (Schedule 6); (6) Counter-signed NDA confirmation. Format: ZIP archive, max 2GB, uploaded via platform submission portal. Deadline: T0+28 23:59 CET (hard cut-off, no extensions). Late submissions auto-rejected. Email verification required. Submission language: English. Currency: EUR.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'submission_guidelines';

UPDATE public.ai_review_section_config SET example_good =
'Success metrics & KPIs (ISO 22400-2 aligned where applicable, measured against matched-site control over a 4-week pilot observation window): (1) Pick productivity — lines per picker-hour, target +10% absolute lift, primary success criterion, statistical significance p<0.05 via two-sample t-test on shift-day pairs; (2) Pick travel distance per order (ISO 22400-2 KPI 14) — target -20%, secondary KPI; (3) Pick-confirmation p95 latency during peak window (14:00–18:00) — must remain below 4.0s, guardrail KPI (no degradation); (4) Order on-time fulfilment rate — must remain above pre-pilot baseline (no regression), guardrail; (5) Picker workload variance (Gini coefficient on shift workload) — must not increase by more than 5% (Works Council fairness commitment); (6) Incident rate (mis-picks per 10k lines) — must remain at or below baseline. Measurement infrastructure pre-built in data room (notebook D-07). Decision rule: primary KPI met AND no guardrail breached → success.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'success_metrics_kpis';

UPDATE public.ai_review_section_config SET example_good =
'Visibility: PRIVATE-INVITED. Challenge is visible only to platform-pool Solvers matching the targeting filters (EU/EEA-based, SAP EWM Gold+/Platinum or qualifying boutique, ≥3 reference engagements). Estimated invited pool: ~140 providers. Discovery model: providers see the challenge in their personalised dashboard upon publication; the challenge does NOT appear in the public Marketplace listing and is NOT indexed for search. Rationale: the brief contains commercially sensitive operational deficiency data (referenced via the data room) and the Seeker prefers a curated funnel to manage Q&A load. Publication moment: T0 = challenge publish event. Delisting: automatic at submission deadline (T0+28). Confidentiality: brief content is confidential under the Mutual NDA from the moment a Solver expresses interest; Solvers must counter-sign before any data-room access. Aligned with Access Type, Solver Audience, and Eligibility.',
updated_at = now()
WHERE role_context = 'curation' AND section_key = 'visibility';
